[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps = 
    knolleary/PubSubClient@^2.8

[env:qemu]
platform = espressif32
board = esp32dev
framework = espidf
build_flags = 
    -DCONFIG_ESP32_DEFAULT_CPU_FREQ_240=1
