//! HMAC-SHA256 signed download URLs for workspace files.
//!
//! URLs carry an expiration timestamp and a signature so the gateway can verify
//! that a link was generated by a trusted component without requiring a session
//! or bearer token (important for click-to-download from chat clients like Lark).

use hmac::{Hmac, Mac};
use sha2::Sha256;
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

/// Default TTL for download URLs: 24 hours.
pub const DEFAULT_TTL_SECS: u64 = 86_400;

/// Build a signed download URL.
///
/// The returned URL has the form:
/// `{base_url}/download/{percent_encoded_path}?expires={unix_ts}&sig={hex_hmac}`
pub fn sign_download_url(base_url: &str, path: &str, secret: &[u8], ttl_secs: u64) -> String {
    let expires = now_unix() + ttl_secs;
    let sig = compute_sig(path, expires, secret);
    let encoded_path = urlencoding::encode(path);
    format!(
        "{}/download/{}?expires={}&sig={}",
        base_url.trim_end_matches('/'),
        encoded_path,
        expires,
        sig,
    )
}

/// Verify a signed download URL's signature and expiration.
pub fn verify_download_url(path: &str, secret: &[u8], expires: u64, sig: &str) -> bool {
    if now_unix() > expires {
        return false;
    }
    let expected = compute_sig(path, expires, secret);
    constant_time_eq(expected.as_bytes(), sig.as_bytes())
}

/// Derive a download secret from the workspace directory path.
///
/// Used as a fallback when `gateway.download_secret` is not explicitly set.
/// Deterministic per installation so URLs survive restarts.
pub fn derive_secret_from_workspace(workspace_dir: &std::path::Path) -> Vec<u8> {
    use sha2::Digest;
    let mut hasher = Sha256::new();
    hasher.update(b"zeroclaw-download-secret:");
    hasher.update(workspace_dir.to_string_lossy().as_bytes());
    hasher.finalize().to_vec()
}

// ── internal helpers ────────────────────────────────────────────

fn compute_sig(path: &str, expires: u64, secret: &[u8]) -> String {
    let mut mac = HmacSha256::new_from_slice(secret).expect("HMAC accepts any key length");
    mac.update(path.as_bytes());
    mac.update(b":");
    mac.update(expires.to_string().as_bytes());
    hex::encode(mac.finalize().into_bytes())
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

/// Constant-time comparison to prevent timing attacks on signature verification.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    a.iter()
        .zip(b.iter())
        .fold(0u8, |acc, (x, y)| acc | (x ^ y))
        == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_and_verify_roundtrip() {
        let secret = b"test-secret-key";
        let url = sign_download_url("https://example.com", "report.md", secret, 3600);
        assert!(url.contains("/download/report.md?expires="));
        assert!(url.contains("&sig="));

        // Extract parts
        let query = url.split('?').nth(1).unwrap();
        let params: std::collections::HashMap<&str, &str> = query
            .split('&')
            .map(|kv| {
                let mut parts = kv.splitn(2, '=');
                (parts.next().unwrap(), parts.next().unwrap())
            })
            .collect();

        let expires: u64 = params["expires"].parse().unwrap();
        let sig = params["sig"];
        assert!(verify_download_url("report.md", secret, expires, sig));
    }

    #[test]
    fn wrong_secret_fails() {
        let secret = b"correct-secret";
        let url = sign_download_url("https://example.com", "file.txt", secret, 3600);

        let query = url.split('?').nth(1).unwrap();
        let params: std::collections::HashMap<&str, &str> = query
            .split('&')
            .map(|kv| {
                let mut parts = kv.splitn(2, '=');
                (parts.next().unwrap(), parts.next().unwrap())
            })
            .collect();

        let expires: u64 = params["expires"].parse().unwrap();
        let sig = params["sig"];
        assert!(!verify_download_url(
            "file.txt",
            b"wrong-secret",
            expires,
            sig
        ));
    }

    #[test]
    fn expired_url_fails() {
        let secret = b"test-secret";
        // Expired 1 second ago
        let expires = now_unix().saturating_sub(1);
        let sig = compute_sig("file.txt", expires, secret);
        assert!(!verify_download_url("file.txt", secret, expires, &sig));
    }

    #[test]
    fn tampered_path_fails() {
        let secret = b"test-secret";
        let expires = now_unix() + 3600;
        let sig = compute_sig("legit.md", expires, secret);
        assert!(!verify_download_url("evil.md", secret, expires, &sig));
    }

    #[test]
    fn path_with_subdirectory() {
        let secret = b"test-secret";
        let url = sign_download_url(
            "https://example.com",
            "reports/2026/summary.md",
            secret,
            3600,
        );
        // Path should be percent-encoded
        assert!(url.contains("reports%2F2026%2Fsummary.md"));

        let query = url.split('?').nth(1).unwrap();
        let params: std::collections::HashMap<&str, &str> = query
            .split('&')
            .map(|kv| {
                let mut parts = kv.splitn(2, '=');
                (parts.next().unwrap(), parts.next().unwrap())
            })
            .collect();

        let expires: u64 = params["expires"].parse().unwrap();
        let sig = params["sig"];
        assert!(verify_download_url(
            "reports/2026/summary.md",
            secret,
            expires,
            sig
        ));
    }

    #[test]
    fn derive_secret_is_deterministic() {
        let path = std::path::Path::new("/home/user/.zeroclaw/workspace");
        let s1 = derive_secret_from_workspace(path);
        let s2 = derive_secret_from_workspace(path);
        assert_eq!(s1, s2);
        assert_eq!(s1.len(), 32); // SHA-256 output
    }

    #[test]
    fn derive_secret_differs_for_different_paths() {
        let s1 = derive_secret_from_workspace(std::path::Path::new("/a"));
        let s2 = derive_secret_from_workspace(std::path::Path::new("/b"));
        assert_ne!(s1, s2);
    }

    #[test]
    fn trailing_slash_on_base_url_is_handled() {
        let url = sign_download_url("https://example.com/", "file.md", b"s", 60);
        assert!(url.starts_with("https://example.com/download/"));
        // No double slash
        assert!(!url.contains("//download"));
    }
}
