/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as NewRouteImport } from './routes/new'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentSwarmRouteImport } from './routes/agent-swarm'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiValidateProviderRouteImport } from './routes/api/validate-provider'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiUpdateCheckRouteImport } from './routes/api/update-check'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionTitleRouteImport } from './routes/api/session-title'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiProviderUsageRouteImport } from './routes/api/provider-usage'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiOpenclawUpdateRouteImport } from './routes/api/openclaw-update'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiModelSwitchRouteImport } from './routes/api/model-switch'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiGatewayDiscoverRouteImport } from './routes/api/gateway-discover'
import { Route as ApiGatewayConfigRouteImport } from './routes/api/gateway-config'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiDebugAnalyzeRouteImport } from './routes/api/debug-analyze'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiConfigPatchRouteImport } from './routes/api/config-patch'
import { Route as ApiConfigGetRouteImport } from './routes/api/config-get'
import { Route as ApiCliAgentsRouteImport } from './routes/api/cli-agents'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiChatAbortRouteImport } from './routes/api/chat-abort'
import { Route as ApiBrowserRouteImport } from './routes/api/browser'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAgentSteerRouteImport } from './routes/api/agent-steer'
import { Route as ApiAgentPauseRouteImport } from './routes/api/agent-pause'
import { Route as ApiAgentKillRouteImport } from './routes/api/agent-kill'
import { Route as ApiAgentActivityRouteImport } from './routes/api/agent-activity'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks/$taskId'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiGatewayUsageRouteImport } from './routes/api/gateway/usage'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway/status'
import { Route as ApiGatewaySessionsRouteImport } from './routes/api/gateway/sessions'
import { Route as ApiGatewayNodesRouteImport } from './routes/api/gateway/nodes'
import { Route as ApiGatewayChannelsRouteImport } from './routes/api/gateway/channels'
import { Route as ApiGatewayAgentsRouteImport } from './routes/api/gateway/agents'
import { Route as ApiEventsRecentRouteImport } from './routes/api/events/recent'
import { Route as ApiDebugStatusRouteImport } from './routes/api/debug/status'
import { Route as ApiDebugReconnectRouteImport } from './routes/api/debug/reconnect'
import { Route as ApiCronUpsertRouteImport } from './routes/api/cron/upsert'
import { Route as ApiCronToggleRouteImport } from './routes/api/cron/toggle'
import { Route as ApiCronRunRouteImport } from './routes/api/cron/run'
import { Route as ApiCronListRouteImport } from './routes/api/cron/list'
import { Route as ApiCronDeleteRouteImport } from './routes/api/cron/delete'
import { Route as ApiBrowserTabsRouteImport } from './routes/api/browser/tabs'
import { Route as ApiBrowserStatusRouteImport } from './routes/api/browser/status'
import { Route as ApiBrowserScreenshotRouteImport } from './routes/api/browser/screenshot'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'
import { Route as ApiCronRunsJobIdRouteImport } from './routes/api/cron/runs/$jobId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSwarmRoute = AgentSwarmRouteImport.update({
  id: '/agent-swarm',
  path: '/agent-swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateProviderRoute = ApiValidateProviderRouteImport.update({
  id: '/api/validate-provider',
  path: '/api/validate-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateCheckRoute = ApiUpdateCheckRouteImport.update({
  id: '/api/update-check',
  path: '/api/update-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionTitleRoute = ApiSessionTitleRouteImport.update({
  id: '/api/session-title',
  path: '/api/session-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderUsageRoute = ApiProviderUsageRouteImport.update({
  id: '/api/provider-usage',
  path: '/api/provider-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawUpdateRoute = ApiOpenclawUpdateRouteImport.update({
  id: '/api/openclaw-update',
  path: '/api/openclaw-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSwitchRoute = ApiModelSwitchRouteImport.update({
  id: '/api/model-switch',
  path: '/api/model-switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayDiscoverRoute = ApiGatewayDiscoverRouteImport.update({
  id: '/api/gateway-discover',
  path: '/api/gateway-discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayConfigRoute = ApiGatewayConfigRouteImport.update({
  id: '/api/gateway-config',
  path: '/api/gateway-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugAnalyzeRoute = ApiDebugAnalyzeRouteImport.update({
  id: '/api/debug-analyze',
  path: '/api/debug-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigPatchRoute = ApiConfigPatchRouteImport.update({
  id: '/api/config-patch',
  path: '/api/config-patch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigGetRoute = ApiConfigGetRouteImport.update({
  id: '/api/config-get',
  path: '/api/config-get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAgentsRoute = ApiCliAgentsRouteImport.update({
  id: '/api/cli-agents',
  path: '/api/cli-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAbortRoute = ApiChatAbortRouteImport.update({
  id: '/api/chat-abort',
  path: '/api/chat-abort',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowserRoute = ApiBrowserRouteImport.update({
  id: '/api/browser',
  path: '/api/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSteerRoute = ApiAgentSteerRouteImport.update({
  id: '/api/agent-steer',
  path: '/api/agent-steer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPauseRoute = ApiAgentPauseRouteImport.update({
  id: '/api/agent-pause',
  path: '/api/agent-pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentKillRoute = ApiAgentKillRouteImport.update({
  id: '/api/agent-kill',
  path: '/api/agent-kill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentActivityRoute = ApiAgentActivityRouteImport.update({
  id: '/api/agent-activity',
  path: '/api/agent-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/api/tasks/$taskId',
  path: '/api/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiGatewayUsageRoute = ApiGatewayUsageRouteImport.update({
  id: '/api/gateway/usage',
  path: '/api/gateway/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway/status',
  path: '/api/gateway/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewaySessionsRoute = ApiGatewaySessionsRouteImport.update({
  id: '/api/gateway/sessions',
  path: '/api/gateway/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayNodesRoute = ApiGatewayNodesRouteImport.update({
  id: '/api/gateway/nodes',
  path: '/api/gateway/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayChannelsRoute = ApiGatewayChannelsRouteImport.update({
  id: '/api/gateway/channels',
  path: '/api/gateway/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayAgentsRoute = ApiGatewayAgentsRouteImport.update({
  id: '/api/gateway/agents',
  path: '/api/gateway/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRecentRoute = ApiEventsRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiDebugStatusRoute = ApiDebugStatusRouteImport.update({
  id: '/api/debug/status',
  path: '/api/debug/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugReconnectRoute = ApiDebugReconnectRouteImport.update({
  id: '/api/debug/reconnect',
  path: '/api/debug/reconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronUpsertRoute = ApiCronUpsertRouteImport.update({
  id: '/upsert',
  path: '/upsert',
  getParentRoute: () => ApiCronRoute,
} as any)
const ApiCronToggleRoute = ApiCronToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiCronRoute,
} as any)
const ApiCronRunRoute = ApiCronRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiCronRoute,
} as any)
const ApiCronListRoute = ApiCronListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiCronRoute,
} as any)
const ApiCronDeleteRoute = ApiCronDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiCronRoute,
} as any)
const ApiBrowserTabsRoute = ApiBrowserTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ApiBrowserRoute,
} as any)
const ApiBrowserStatusRoute = ApiBrowserStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiBrowserRoute,
} as any)
const ApiBrowserScreenshotRoute = ApiBrowserScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => ApiBrowserRoute,
} as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiCronRunsJobIdRoute = ApiCronRunsJobIdRouteImport.update({
  id: '/runs/$jobId',
  path: '/runs/$jobId',
  getParentRoute: () => ApiCronRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/agent-swarm': typeof AgentSwarmRoute
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/api/agent-activity': typeof ApiAgentActivityRoute
  '/api/agent-kill': typeof ApiAgentKillRoute
  '/api/agent-pause': typeof ApiAgentPauseRoute
  '/api/agent-steer': typeof ApiAgentSteerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/browser': typeof ApiBrowserRouteWithChildren
  '/api/chat-abort': typeof ApiChatAbortRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/cli-agents': typeof ApiCliAgentsRoute
  '/api/config-get': typeof ApiConfigGetRoute
  '/api/config-patch': typeof ApiConfigPatchRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/cost': typeof ApiCostRoute
  '/api/cron': typeof ApiCronRouteWithChildren
  '/api/debug-analyze': typeof ApiDebugAnalyzeRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-config': typeof ApiGatewayConfigRoute
  '/api/gateway-discover': typeof ApiGatewayDiscoverRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/model-switch': typeof ApiModelSwitchRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openclaw-update': typeof ApiOpenclawUpdateRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/provider-usage': typeof ApiProviderUsageRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/update-check': typeof ApiUpdateCheckRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/validate-provider': typeof ApiValidateProviderRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/browser/screenshot': typeof ApiBrowserScreenshotRoute
  '/api/browser/status': typeof ApiBrowserStatusRoute
  '/api/browser/tabs': typeof ApiBrowserTabsRoute
  '/api/cron/delete': typeof ApiCronDeleteRoute
  '/api/cron/list': typeof ApiCronListRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/cron/toggle': typeof ApiCronToggleRoute
  '/api/cron/upsert': typeof ApiCronUpsertRoute
  '/api/debug/reconnect': typeof ApiDebugReconnectRoute
  '/api/debug/status': typeof ApiDebugStatusRoute
  '/api/events/recent': typeof ApiEventsRecentRoute
  '/api/gateway/agents': typeof ApiGatewayAgentsRoute
  '/api/gateway/channels': typeof ApiGatewayChannelsRoute
  '/api/gateway/nodes': typeof ApiGatewayNodesRoute
  '/api/gateway/sessions': typeof ApiGatewaySessionsRoute
  '/api/gateway/status': typeof ApiGatewayStatusRoute
  '/api/gateway/usage': typeof ApiGatewayUsageRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/cron/runs/$jobId': typeof ApiCronRunsJobIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/agent-swarm': typeof AgentSwarmRoute
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/sessions': typeof SessionsRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/api/agent-activity': typeof ApiAgentActivityRoute
  '/api/agent-kill': typeof ApiAgentKillRoute
  '/api/agent-pause': typeof ApiAgentPauseRoute
  '/api/agent-steer': typeof ApiAgentSteerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/browser': typeof ApiBrowserRouteWithChildren
  '/api/chat-abort': typeof ApiChatAbortRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/cli-agents': typeof ApiCliAgentsRoute
  '/api/config-get': typeof ApiConfigGetRoute
  '/api/config-patch': typeof ApiConfigPatchRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/cost': typeof ApiCostRoute
  '/api/cron': typeof ApiCronRouteWithChildren
  '/api/debug-analyze': typeof ApiDebugAnalyzeRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-config': typeof ApiGatewayConfigRoute
  '/api/gateway-discover': typeof ApiGatewayDiscoverRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/model-switch': typeof ApiModelSwitchRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openclaw-update': typeof ApiOpenclawUpdateRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/provider-usage': typeof ApiProviderUsageRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/update-check': typeof ApiUpdateCheckRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/validate-provider': typeof ApiValidateProviderRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/browser/screenshot': typeof ApiBrowserScreenshotRoute
  '/api/browser/status': typeof ApiBrowserStatusRoute
  '/api/browser/tabs': typeof ApiBrowserTabsRoute
  '/api/cron/delete': typeof ApiCronDeleteRoute
  '/api/cron/list': typeof ApiCronListRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/cron/toggle': typeof ApiCronToggleRoute
  '/api/cron/upsert': typeof ApiCronUpsertRoute
  '/api/debug/reconnect': typeof ApiDebugReconnectRoute
  '/api/debug/status': typeof ApiDebugStatusRoute
  '/api/events/recent': typeof ApiEventsRecentRoute
  '/api/gateway/agents': typeof ApiGatewayAgentsRoute
  '/api/gateway/channels': typeof ApiGatewayChannelsRoute
  '/api/gateway/nodes': typeof ApiGatewayNodesRoute
  '/api/gateway/sessions': typeof ApiGatewaySessionsRoute
  '/api/gateway/status': typeof ApiGatewayStatusRoute
  '/api/gateway/usage': typeof ApiGatewayUsageRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/cron/runs/$jobId': typeof ApiCronRunsJobIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/agent-swarm': typeof AgentSwarmRoute
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/channels': typeof ChannelsRoute
  '/connect': typeof ConnectRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/files': typeof FilesRoute
  '/instances': typeof InstancesRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/api/agent-activity': typeof ApiAgentActivityRoute
  '/api/agent-kill': typeof ApiAgentKillRoute
  '/api/agent-pause': typeof ApiAgentPauseRoute
  '/api/agent-steer': typeof ApiAgentSteerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/browser': typeof ApiBrowserRouteWithChildren
  '/api/chat-abort': typeof ApiChatAbortRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/cli-agents': typeof ApiCliAgentsRoute
  '/api/config-get': typeof ApiConfigGetRoute
  '/api/config-patch': typeof ApiConfigPatchRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/cost': typeof ApiCostRoute
  '/api/cron': typeof ApiCronRouteWithChildren
  '/api/debug-analyze': typeof ApiDebugAnalyzeRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-config': typeof ApiGatewayConfigRoute
  '/api/gateway-discover': typeof ApiGatewayDiscoverRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/model-switch': typeof ApiModelSwitchRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openclaw-update': typeof ApiOpenclawUpdateRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/provider-usage': typeof ApiProviderUsageRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/session-title': typeof ApiSessionTitleRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/update-check': typeof ApiUpdateCheckRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/validate-provider': typeof ApiValidateProviderRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/browser/screenshot': typeof ApiBrowserScreenshotRoute
  '/api/browser/status': typeof ApiBrowserStatusRoute
  '/api/browser/tabs': typeof ApiBrowserTabsRoute
  '/api/cron/delete': typeof ApiCronDeleteRoute
  '/api/cron/list': typeof ApiCronListRoute
  '/api/cron/run': typeof ApiCronRunRoute
  '/api/cron/toggle': typeof ApiCronToggleRoute
  '/api/cron/upsert': typeof ApiCronUpsertRoute
  '/api/debug/reconnect': typeof ApiDebugReconnectRoute
  '/api/debug/status': typeof ApiDebugStatusRoute
  '/api/events/recent': typeof ApiEventsRecentRoute
  '/api/gateway/agents': typeof ApiGatewayAgentsRoute
  '/api/gateway/channels': typeof ApiGatewayChannelsRoute
  '/api/gateway/nodes': typeof ApiGatewayNodesRoute
  '/api/gateway/sessions': typeof ApiGatewaySessionsRoute
  '/api/gateway/status': typeof ApiGatewayStatusRoute
  '/api/gateway/usage': typeof ApiGatewayUsageRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/cron/runs/$jobId': typeof ApiCronRunsJobIdRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/activity'
    | '/agent-swarm'
    | '/agents'
    | '/browser'
    | '/channels'
    | '/connect'
    | '/cron'
    | '/dashboard'
    | '/debug'
    | '/files'
    | '/instances'
    | '/logs'
    | '/memory'
    | '/new'
    | '/nodes'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/api/agent-activity'
    | '/api/agent-kill'
    | '/api/agent-pause'
    | '/api/agent-steer'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/browser'
    | '/api/chat-abort'
    | '/api/chat-events'
    | '/api/cli-agents'
    | '/api/config-get'
    | '/api/config-patch'
    | '/api/context-usage'
    | '/api/cost'
    | '/api/cron'
    | '/api/debug-analyze'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-config'
    | '/api/gateway-discover'
    | '/api/history'
    | '/api/model-switch'
    | '/api/models'
    | '/api/openclaw-update'
    | '/api/paths'
    | '/api/ping'
    | '/api/provider-usage'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/session-title'
    | '/api/sessions'
    | '/api/skills'
    | '/api/stream'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/update-check'
    | '/api/usage'
    | '/api/validate-provider'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/browser/screenshot'
    | '/api/browser/status'
    | '/api/browser/tabs'
    | '/api/cron/delete'
    | '/api/cron/list'
    | '/api/cron/run'
    | '/api/cron/toggle'
    | '/api/cron/upsert'
    | '/api/debug/reconnect'
    | '/api/debug/status'
    | '/api/events/recent'
    | '/api/gateway/agents'
    | '/api/gateway/channels'
    | '/api/gateway/nodes'
    | '/api/gateway/sessions'
    | '/api/gateway/status'
    | '/api/gateway/usage'
    | '/api/sessions/send'
    | '/api/tasks/$taskId'
    | '/api/tasks/'
    | '/api/cron/runs/$jobId'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/activity'
    | '/agent-swarm'
    | '/agents'
    | '/browser'
    | '/channels'
    | '/connect'
    | '/cron'
    | '/dashboard'
    | '/debug'
    | '/files'
    | '/instances'
    | '/logs'
    | '/memory'
    | '/new'
    | '/nodes'
    | '/sessions'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/api/agent-activity'
    | '/api/agent-kill'
    | '/api/agent-pause'
    | '/api/agent-steer'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/browser'
    | '/api/chat-abort'
    | '/api/chat-events'
    | '/api/cli-agents'
    | '/api/config-get'
    | '/api/config-patch'
    | '/api/context-usage'
    | '/api/cost'
    | '/api/cron'
    | '/api/debug-analyze'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-config'
    | '/api/gateway-discover'
    | '/api/history'
    | '/api/model-switch'
    | '/api/models'
    | '/api/openclaw-update'
    | '/api/paths'
    | '/api/ping'
    | '/api/provider-usage'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/session-title'
    | '/api/sessions'
    | '/api/skills'
    | '/api/stream'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/update-check'
    | '/api/usage'
    | '/api/validate-provider'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat'
    | '/settings'
    | '/api/browser/screenshot'
    | '/api/browser/status'
    | '/api/browser/tabs'
    | '/api/cron/delete'
    | '/api/cron/list'
    | '/api/cron/run'
    | '/api/cron/toggle'
    | '/api/cron/upsert'
    | '/api/debug/reconnect'
    | '/api/debug/status'
    | '/api/events/recent'
    | '/api/gateway/agents'
    | '/api/gateway/channels'
    | '/api/gateway/nodes'
    | '/api/gateway/sessions'
    | '/api/gateway/status'
    | '/api/gateway/usage'
    | '/api/sessions/send'
    | '/api/tasks/$taskId'
    | '/api/tasks'
    | '/api/cron/runs/$jobId'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/activity'
    | '/agent-swarm'
    | '/agents'
    | '/browser'
    | '/channels'
    | '/connect'
    | '/cron'
    | '/dashboard'
    | '/debug'
    | '/files'
    | '/instances'
    | '/logs'
    | '/memory'
    | '/new'
    | '/nodes'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/api/agent-activity'
    | '/api/agent-kill'
    | '/api/agent-pause'
    | '/api/agent-steer'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/browser'
    | '/api/chat-abort'
    | '/api/chat-events'
    | '/api/cli-agents'
    | '/api/config-get'
    | '/api/config-patch'
    | '/api/context-usage'
    | '/api/cost'
    | '/api/cron'
    | '/api/debug-analyze'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-config'
    | '/api/gateway-discover'
    | '/api/history'
    | '/api/model-switch'
    | '/api/models'
    | '/api/openclaw-update'
    | '/api/paths'
    | '/api/ping'
    | '/api/provider-usage'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/session-title'
    | '/api/sessions'
    | '/api/skills'
    | '/api/stream'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/update-check'
    | '/api/usage'
    | '/api/validate-provider'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/browser/screenshot'
    | '/api/browser/status'
    | '/api/browser/tabs'
    | '/api/cron/delete'
    | '/api/cron/list'
    | '/api/cron/run'
    | '/api/cron/toggle'
    | '/api/cron/upsert'
    | '/api/debug/reconnect'
    | '/api/debug/status'
    | '/api/events/recent'
    | '/api/gateway/agents'
    | '/api/gateway/channels'
    | '/api/gateway/nodes'
    | '/api/gateway/sessions'
    | '/api/gateway/status'
    | '/api/gateway/usage'
    | '/api/sessions/send'
    | '/api/tasks/$taskId'
    | '/api/tasks/'
    | '/api/cron/runs/$jobId'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ActivityRoute: typeof ActivityRoute
  AgentSwarmRoute: typeof AgentSwarmRoute
  AgentsRoute: typeof AgentsRoute
  BrowserRoute: typeof BrowserRoute
  ChannelsRoute: typeof ChannelsRoute
  ConnectRoute: typeof ConnectRoute
  CronRoute: typeof CronRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  FilesRoute: typeof FilesRoute
  InstancesRoute: typeof InstancesRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  NewRoute: typeof NewRoute
  NodesRoute: typeof NodesRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  TerminalRoute: typeof TerminalRoute
  UsageRoute: typeof UsageRoute
  ApiAgentActivityRoute: typeof ApiAgentActivityRoute
  ApiAgentKillRoute: typeof ApiAgentKillRoute
  ApiAgentPauseRoute: typeof ApiAgentPauseRoute
  ApiAgentSteerRoute: typeof ApiAgentSteerRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiBrowserRoute: typeof ApiBrowserRouteWithChildren
  ApiChatAbortRoute: typeof ApiChatAbortRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiCliAgentsRoute: typeof ApiCliAgentsRoute
  ApiConfigGetRoute: typeof ApiConfigGetRoute
  ApiConfigPatchRoute: typeof ApiConfigPatchRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiCostRoute: typeof ApiCostRoute
  ApiCronRoute: typeof ApiCronRouteWithChildren
  ApiDebugAnalyzeRoute: typeof ApiDebugAnalyzeRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayConfigRoute: typeof ApiGatewayConfigRoute
  ApiGatewayDiscoverRoute: typeof ApiGatewayDiscoverRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiModelSwitchRoute: typeof ApiModelSwitchRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiOpenclawUpdateRoute: typeof ApiOpenclawUpdateRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiProviderUsageRoute: typeof ApiProviderUsageRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionTitleRoute: typeof ApiSessionTitleRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiUpdateCheckRoute: typeof ApiUpdateCheckRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiValidateProviderRoute: typeof ApiValidateProviderRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiDebugReconnectRoute: typeof ApiDebugReconnectRoute
  ApiDebugStatusRoute: typeof ApiDebugStatusRoute
  ApiGatewayAgentsRoute: typeof ApiGatewayAgentsRoute
  ApiGatewayChannelsRoute: typeof ApiGatewayChannelsRoute
  ApiGatewayNodesRoute: typeof ApiGatewayNodesRoute
  ApiGatewaySessionsRoute: typeof ApiGatewaySessionsRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiGatewayUsageRoute: typeof ApiGatewayUsageRoute
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-swarm': {
      id: '/agent-swarm'
      path: '/agent-swarm'
      fullPath: '/agent-swarm'
      preLoaderRoute: typeof AgentSwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate-provider': {
      id: '/api/validate-provider'
      path: '/api/validate-provider'
      fullPath: '/api/validate-provider'
      preLoaderRoute: typeof ApiValidateProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-check': {
      id: '/api/update-check'
      path: '/api/update-check'
      fullPath: '/api/update-check'
      preLoaderRoute: typeof ApiUpdateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-title': {
      id: '/api/session-title'
      path: '/api/session-title'
      fullPath: '/api/session-title'
      preLoaderRoute: typeof ApiSessionTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-usage': {
      id: '/api/provider-usage'
      path: '/api/provider-usage'
      fullPath: '/api/provider-usage'
      preLoaderRoute: typeof ApiProviderUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw-update': {
      id: '/api/openclaw-update'
      path: '/api/openclaw-update'
      fullPath: '/api/openclaw-update'
      preLoaderRoute: typeof ApiOpenclawUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model-switch': {
      id: '/api/model-switch'
      path: '/api/model-switch'
      fullPath: '/api/model-switch'
      preLoaderRoute: typeof ApiModelSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-discover': {
      id: '/api/gateway-discover'
      path: '/api/gateway-discover'
      fullPath: '/api/gateway-discover'
      preLoaderRoute: typeof ApiGatewayDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-config': {
      id: '/api/gateway-config'
      path: '/api/gateway-config'
      fullPath: '/api/gateway-config'
      preLoaderRoute: typeof ApiGatewayConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-analyze': {
      id: '/api/debug-analyze'
      path: '/api/debug-analyze'
      fullPath: '/api/debug-analyze'
      preLoaderRoute: typeof ApiDebugAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config-patch': {
      id: '/api/config-patch'
      path: '/api/config-patch'
      fullPath: '/api/config-patch'
      preLoaderRoute: typeof ApiConfigPatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config-get': {
      id: '/api/config-get'
      path: '/api/config-get'
      fullPath: '/api/config-get'
      preLoaderRoute: typeof ApiConfigGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli-agents': {
      id: '/api/cli-agents'
      path: '/api/cli-agents'
      fullPath: '/api/cli-agents'
      preLoaderRoute: typeof ApiCliAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-abort': {
      id: '/api/chat-abort'
      path: '/api/chat-abort'
      fullPath: '/api/chat-abort'
      preLoaderRoute: typeof ApiChatAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browser': {
      id: '/api/browser'
      path: '/api/browser'
      fullPath: '/api/browser'
      preLoaderRoute: typeof ApiBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-steer': {
      id: '/api/agent-steer'
      path: '/api/agent-steer'
      fullPath: '/api/agent-steer'
      preLoaderRoute: typeof ApiAgentSteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-pause': {
      id: '/api/agent-pause'
      path: '/api/agent-pause'
      fullPath: '/api/agent-pause'
      preLoaderRoute: typeof ApiAgentPauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-kill': {
      id: '/api/agent-kill'
      path: '/api/agent-kill'
      fullPath: '/api/agent-kill'
      preLoaderRoute: typeof ApiAgentKillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-activity': {
      id: '/api/agent-activity'
      path: '/api/agent-activity'
      fullPath: '/api/agent-activity'
      preLoaderRoute: typeof ApiAgentActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks/'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/api/tasks/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/gateway/usage': {
      id: '/api/gateway/usage'
      path: '/api/gateway/usage'
      fullPath: '/api/gateway/usage'
      preLoaderRoute: typeof ApiGatewayUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/status': {
      id: '/api/gateway/status'
      path: '/api/gateway/status'
      fullPath: '/api/gateway/status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/sessions': {
      id: '/api/gateway/sessions'
      path: '/api/gateway/sessions'
      fullPath: '/api/gateway/sessions'
      preLoaderRoute: typeof ApiGatewaySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/nodes': {
      id: '/api/gateway/nodes'
      path: '/api/gateway/nodes'
      fullPath: '/api/gateway/nodes'
      preLoaderRoute: typeof ApiGatewayNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/channels': {
      id: '/api/gateway/channels'
      path: '/api/gateway/channels'
      fullPath: '/api/gateway/channels'
      preLoaderRoute: typeof ApiGatewayChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway/agents': {
      id: '/api/gateway/agents'
      path: '/api/gateway/agents'
      fullPath: '/api/gateway/agents'
      preLoaderRoute: typeof ApiGatewayAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/recent': {
      id: '/api/events/recent'
      path: '/recent'
      fullPath: '/api/events/recent'
      preLoaderRoute: typeof ApiEventsRecentRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/debug/status': {
      id: '/api/debug/status'
      path: '/api/debug/status'
      fullPath: '/api/debug/status'
      preLoaderRoute: typeof ApiDebugStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/reconnect': {
      id: '/api/debug/reconnect'
      path: '/api/debug/reconnect'
      fullPath: '/api/debug/reconnect'
      preLoaderRoute: typeof ApiDebugReconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/upsert': {
      id: '/api/cron/upsert'
      path: '/upsert'
      fullPath: '/api/cron/upsert'
      preLoaderRoute: typeof ApiCronUpsertRouteImport
      parentRoute: typeof ApiCronRoute
    }
    '/api/cron/toggle': {
      id: '/api/cron/toggle'
      path: '/toggle'
      fullPath: '/api/cron/toggle'
      preLoaderRoute: typeof ApiCronToggleRouteImport
      parentRoute: typeof ApiCronRoute
    }
    '/api/cron/run': {
      id: '/api/cron/run'
      path: '/run'
      fullPath: '/api/cron/run'
      preLoaderRoute: typeof ApiCronRunRouteImport
      parentRoute: typeof ApiCronRoute
    }
    '/api/cron/list': {
      id: '/api/cron/list'
      path: '/list'
      fullPath: '/api/cron/list'
      preLoaderRoute: typeof ApiCronListRouteImport
      parentRoute: typeof ApiCronRoute
    }
    '/api/cron/delete': {
      id: '/api/cron/delete'
      path: '/delete'
      fullPath: '/api/cron/delete'
      preLoaderRoute: typeof ApiCronDeleteRouteImport
      parentRoute: typeof ApiCronRoute
    }
    '/api/browser/tabs': {
      id: '/api/browser/tabs'
      path: '/tabs'
      fullPath: '/api/browser/tabs'
      preLoaderRoute: typeof ApiBrowserTabsRouteImport
      parentRoute: typeof ApiBrowserRoute
    }
    '/api/browser/status': {
      id: '/api/browser/status'
      path: '/status'
      fullPath: '/api/browser/status'
      preLoaderRoute: typeof ApiBrowserStatusRouteImport
      parentRoute: typeof ApiBrowserRoute
    }
    '/api/browser/screenshot': {
      id: '/api/browser/screenshot'
      path: '/screenshot'
      fullPath: '/api/browser/screenshot'
      preLoaderRoute: typeof ApiBrowserScreenshotRouteImport
      parentRoute: typeof ApiBrowserRoute
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/cron/runs/$jobId': {
      id: '/api/cron/runs/$jobId'
      path: '/runs/$jobId'
      fullPath: '/api/cron/runs/$jobId'
      preLoaderRoute: typeof ApiCronRunsJobIdRouteImport
      parentRoute: typeof ApiCronRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiBrowserRouteChildren {
  ApiBrowserScreenshotRoute: typeof ApiBrowserScreenshotRoute
  ApiBrowserStatusRoute: typeof ApiBrowserStatusRoute
  ApiBrowserTabsRoute: typeof ApiBrowserTabsRoute
}

const ApiBrowserRouteChildren: ApiBrowserRouteChildren = {
  ApiBrowserScreenshotRoute: ApiBrowserScreenshotRoute,
  ApiBrowserStatusRoute: ApiBrowserStatusRoute,
  ApiBrowserTabsRoute: ApiBrowserTabsRoute,
}

const ApiBrowserRouteWithChildren = ApiBrowserRoute._addFileChildren(
  ApiBrowserRouteChildren,
)

interface ApiCronRouteChildren {
  ApiCronDeleteRoute: typeof ApiCronDeleteRoute
  ApiCronListRoute: typeof ApiCronListRoute
  ApiCronRunRoute: typeof ApiCronRunRoute
  ApiCronToggleRoute: typeof ApiCronToggleRoute
  ApiCronUpsertRoute: typeof ApiCronUpsertRoute
  ApiCronRunsJobIdRoute: typeof ApiCronRunsJobIdRoute
}

const ApiCronRouteChildren: ApiCronRouteChildren = {
  ApiCronDeleteRoute: ApiCronDeleteRoute,
  ApiCronListRoute: ApiCronListRoute,
  ApiCronRunRoute: ApiCronRunRoute,
  ApiCronToggleRoute: ApiCronToggleRoute,
  ApiCronUpsertRoute: ApiCronUpsertRoute,
  ApiCronRunsJobIdRoute: ApiCronRunsJobIdRoute,
}

const ApiCronRouteWithChildren =
  ApiCronRoute._addFileChildren(ApiCronRouteChildren)

interface ApiEventsRouteChildren {
  ApiEventsRecentRoute: typeof ApiEventsRecentRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsRecentRoute: ApiEventsRecentRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActivityRoute: ActivityRoute,
  AgentSwarmRoute: AgentSwarmRoute,
  AgentsRoute: AgentsRoute,
  BrowserRoute: BrowserRoute,
  ChannelsRoute: ChannelsRoute,
  ConnectRoute: ConnectRoute,
  CronRoute: CronRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  FilesRoute: FilesRoute,
  InstancesRoute: InstancesRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  NewRoute: NewRoute,
  NodesRoute: NodesRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  TerminalRoute: TerminalRoute,
  UsageRoute: UsageRoute,
  ApiAgentActivityRoute: ApiAgentActivityRoute,
  ApiAgentKillRoute: ApiAgentKillRoute,
  ApiAgentPauseRoute: ApiAgentPauseRoute,
  ApiAgentSteerRoute: ApiAgentSteerRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiBrowserRoute: ApiBrowserRouteWithChildren,
  ApiChatAbortRoute: ApiChatAbortRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiCliAgentsRoute: ApiCliAgentsRoute,
  ApiConfigGetRoute: ApiConfigGetRoute,
  ApiConfigPatchRoute: ApiConfigPatchRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiCostRoute: ApiCostRoute,
  ApiCronRoute: ApiCronRouteWithChildren,
  ApiDebugAnalyzeRoute: ApiDebugAnalyzeRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayConfigRoute: ApiGatewayConfigRoute,
  ApiGatewayDiscoverRoute: ApiGatewayDiscoverRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiModelSwitchRoute: ApiModelSwitchRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiOpenclawUpdateRoute: ApiOpenclawUpdateRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiProviderUsageRoute: ApiProviderUsageRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionTitleRoute: ApiSessionTitleRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiUpdateCheckRoute: ApiUpdateCheckRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiValidateProviderRoute: ApiValidateProviderRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiDebugReconnectRoute: ApiDebugReconnectRoute,
  ApiDebugStatusRoute: ApiDebugStatusRoute,
  ApiGatewayAgentsRoute: ApiGatewayAgentsRoute,
  ApiGatewayChannelsRoute: ApiGatewayChannelsRoute,
  ApiGatewayNodesRoute: ApiGatewayNodesRoute,
  ApiGatewaySessionsRoute: ApiGatewaySessionsRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiGatewayUsageRoute: ApiGatewayUsageRoute,
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
