"type: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
          - "**/*.mdx"
          - "LICENSE"
          - ".markdownlint-cli2.yaml"

"type: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "Cargo.toml"
          - "Cargo.lock"
          - "deny.toml"
          - ".github/dependabot.yml"

"type: ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".githooks/**"

"area: agent":
  - changed-files:
      - any-glob-to-any-file:
          - "src/agent/**"

"area: gateway":
  - changed-files:
      - any-glob-to-any-file:
          - "src/gateway/**"

"area: config":
  - changed-files:
      - any-glob-to-any-file:
          - "src/config/**"

"area: integrations":
  - changed-files:
      - any-glob-to-any-file:
          - "src/integrations/**"

"area: providers":
  - changed-files:
      - any-glob-to-any-file:
          - "src/providers/**"

"area: channels":
  - changed-files:
      - any-glob-to-any-file:
          - "src/channels/**"

"area: memory":
  - changed-files:
      - any-glob-to-any-file:
          - "src/memory/**"

"area: security":
  - changed-files:
      - any-glob-to-any-file:
          - "src/security/**"

"area: runtime":
  - changed-files:
      - any-glob-to-any-file:
          - "src/runtime/**"

"area: tools":
  - changed-files:
      - any-glob-to-any-file:
          - "src/tools/**"

"area: observability":
  - changed-files:
      - any-glob-to-any-file:
          - "src/observability/**"

"area: tests":
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

"area: scripts":
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"

"area: dev":
  - changed-files:
      - any-glob-to-any-file:
          - "dev/**"
