[workspace]
changelog_update = true
git_tag_enable = true
semver_check = false

[[package]]
name = "zeroclaw-api"
semver_check = true

[[package]]
name = "aardvark-sys"
release = false

[[package]]
name = "robot-kit"
release = false
