// Host-side WIT bindings generated by `wasmtime::component::bindgen!`.
// Each world is namespaced in its own module to prevent the three
// bindgen! invocations from generating conflicting `exports` / `zeroclaw`
// module names in the same scope.
// These are internal to the `component` module — consumers use the adapter
// structs (`ComponentTool`, `ComponentMemory`, `ComponentChannel`) instead.

pub mod tool {
    wasmtime::component::bindgen!({
        world: "tool-plugin",
        path: "../../wit/v0",
        imports: { default: async },
        exports: { default: async }
    });
}
pub mod memory {
    wasmtime::component::bindgen!({
        world: "memory-plugin",
        path: "../../wit/v0",
        imports: {
            default: async,
        },
        exports: {
            // Most exports are async, but these need to be sync.
            "zeroclaw:plugin/plugin-info.plugin-name": trappable,
            "zeroclaw:plugin/plugin-info.plugin-version": trappable,
            "zeroclaw:plugin/memory.get-memory-capabilities": trappable,
            default: async
        }
    });
}
pub mod channel {
    wasmtime::component::bindgen!({
        world: "channel-plugin",
        path: "../../wit/v0",
        imports: {
            default: async,
        },
        exports: {
            // Most exports are async, but these need to be sync.
            "zeroclaw:plugin/plugin-info.plugin-name": trappable,
            "zeroclaw:plugin/plugin-info.plugin-version": trappable,
            "zeroclaw:plugin/channel.get-channel-capabilities": trappable,
            "zeroclaw:plugin/channel.self-handle": trappable,
            "zeroclaw:plugin/channel.self-addressed-mention": trappable,
            "zeroclaw:plugin/channel.drop-self-message": trappable,
            "zeroclaw:plugin/channel.multi-message-delay-ms": trappable,
            default: async
        }
    });
}
