// Host-side WIT bindings generated by `wasmtime::component::bindgen!`.
// Each world is namespaced in its own module to prevent the three
// bindgen! invocations from generating conflicting `exports` / `zeroclaw`
// module names in the same scope.
// These are internal to the `component` module — consumers use the adapter
// structs (`ComponentTool`, `ComponentMemory`, `ComponentChannel`) instead.

pub mod tool {
    wasmtime::component::bindgen!({
        world: "tool-plugin",
        path: "../../wit/v0",
        imports: { default: async },
        exports: { default: async }
    });
}
// `trappable` (sync) export overrides were tried here for the handful of
// metadata-only functions (plugin-info, get-*-capabilities, etc.) but
// wasmtime's `validate_sync_call` rejects any sync export call once a
// store has async-required imports wired in (which `imports: { default:
// async }` always does) — every export must go through the `_async` call
// path on this host, with no sync-call exception.
pub mod memory {
    wasmtime::component::bindgen!({
        world: "memory-plugin",
        path: "../../wit/v0",
        imports: {
            default: async,
        },
        exports: {
            default: async
        }
    });
}
pub mod channel {
    wasmtime::component::bindgen!({
        world: "channel-plugin",
        path: "../../wit/v0",
        imports: {
            default: async,
        },
        exports: {
            default: async
        },
        with: {
            // The `websocket`/`gateway-session` resources' representation
            // types live in their own host modules so the host
            // implementation can use `ResourceTable`'s typed helpers
            // directly.
            "zeroclaw:plugin/websocket.websocket": super::super::websocket_host::HostWebsocketState,
            "zeroclaw:plugin/gateway.gateway-session": super::super::gateway_host::HostGatewaySessionState,
        }
    });
}
