import type { ChannelSchema } from "@/types/api";

export const CHANNEL_SCHEMAS: ChannelSchema[] = [
  {
    channel_key: "telegram",
    display_name: "Telegram",
    description: "Bot de Telegram via BotFather",
    fields: [
      {
        name: "bot_token",
        label: "Bot Token",
        type: "password",
        required: true,
        placeholder: "123456789:AAH...",
      },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
        placeholder: "User ID or @username",
        help_text: "Telegram user IDs or usernames. Empty = deny all.",
      },
      {
        name: "stream_mode",
        label: "Stream Mode",
        type: "select",
        required: false,
        options: ["off", "partial"],
        default_value: "off",
        help_text: "Progressive response delivery via message edits.",
      },
      {
        name: "draft_update_interval_ms",
        label: "Draft Update Interval (ms)",
        type: "number",
        required: false,
        default_value: 1000,
      },
      {
        name: "interrupt_on_new_message",
        label: "Interrupt on New Message",
        type: "boolean",
        required: false,
        default_value: false,
      },
      {
        name: "mention_only",
        label: "Mention Only (Groups)",
        type: "boolean",
        required: false,
        default_value: false,
      },
    ],
  },
  {
    channel_key: "discord",
    display_name: "Discord",
    description: "Bot de Discord",
    fields: [
      {
        name: "bot_token",
        label: "Bot Token",
        type: "password",
        required: true,
        placeholder: "MTk...",
      },
      {
        name: "guild_id",
        label: "Guild ID",
        type: "text",
        required: false,
        placeholder: "Optional server ID",
      },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
        placeholder: "Discord user ID",
      },
      {
        name: "listen_to_bots",
        label: "Listen to Bots",
        type: "boolean",
        required: false,
        default_value: false,
      },
      {
        name: "mention_only",
        label: "Mention Only",
        type: "boolean",
        required: false,
        default_value: false,
      },
    ],
  },
  {
    channel_key: "slack",
    display_name: "Slack",
    description: "Bot de Slack",
    fields: [
      {
        name: "bot_token",
        label: "Bot Token",
        type: "password",
        required: true,
        placeholder: "xoxb-...",
      },
      {
        name: "app_token",
        label: "App Token",
        type: "password",
        required: false,
        placeholder: "xapp-...",
      },
      {
        name: "channel_id",
        label: "Channel ID",
        type: "text",
        required: false,
        placeholder: "C01234567",
      },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
        placeholder: "Slack user ID",
      },
      {
        name: "interrupt_on_new_message",
        label: "Interrupt on New Message",
        type: "boolean",
        required: false,
        default_value: false,
      },
    ],
  },
  {
    channel_key: "whatsapp",
    display_name: "WhatsApp",
    description: "Cloud API (Meta Business) or Web mode (QR pairing)",
    fields: [
      // Cloud API fields
      {
        name: "access_token",
        label: "Access Token (Cloud API)",
        type: "password",
        required: false,
        placeholder: "EAAxxxxxx...",
        help_text: "Token from Meta Business Suite. Leave empty for Web mode.",
      },
      {
        name: "phone_number_id",
        label: "Phone Number ID (Cloud API)",
        type: "text",
        required: false,
        placeholder: "123456789",
      },
      {
        name: "verify_token",
        label: "Verify Token (Cloud API)",
        type: "password",
        required: false,
        placeholder: "Your webhook verify token",
      },
      {
        name: "app_secret",
        label: "App Secret (Cloud API)",
        type: "password",
        required: false,
        placeholder: "abc123...",
        help_text: "For webhook signature verification.",
      },
      // Web mode fields
      {
        name: "session_path",
        label: "Session Path (Web/QR)",
        type: "text",
        required: false,
        placeholder: "whatsapp_session.db",
        help_text: "Set this to enable Web mode with QR pairing.",
      },
      {
        name: "pair_phone",
        label: "Pair Phone (Web)",
        type: "text",
        required: false,
        placeholder: "56912345678",
        help_text: "Phone number without +. If empty, QR code pairing is used.",
      },
      {
        name: "pair_code",
        label: "Pair Code (Web)",
        type: "text",
        required: false,
        placeholder: "Leave empty for auto-generated",
      },
      // Shared
      {
        name: "allowed_senders",
        label: "Allowed Senders",
        type: "string_array",
        required: false,
        placeholder: "+56912345678 or *",
        help_text: "E.164 format. Use * to allow all.",
      },
    ],
  },
  {
    channel_key: "signal",
    display_name: "Signal",
    description: "Via signal-cli REST API",
    fields: [
      {
        name: "http_url",
        label: "Signal CLI HTTP URL",
        type: "text",
        required: true,
        placeholder: "http://localhost:8080",
      },
      {
        name: "account",
        label: "Account (Phone)",
        type: "text",
        required: true,
        placeholder: "+1234567890",
        help_text: "E.164 format phone number.",
      },
      {
        name: "group_id",
        label: "Group ID",
        type: "text",
        required: false,
        placeholder: "Leave empty for DMs, or group ID",
      },
      {
        name: "allowed_from",
        label: "Allowed From",
        type: "string_array",
        required: false,
        placeholder: "+1234567890",
      },
      {
        name: "ignore_attachments",
        label: "Ignore Attachments",
        type: "boolean",
        required: false,
        default_value: false,
      },
      {
        name: "ignore_stories",
        label: "Ignore Stories",
        type: "boolean",
        required: false,
        default_value: false,
      },
    ],
  },
  {
    channel_key: "matrix",
    display_name: "Matrix",
    description: "Decentralized messaging protocol",
    fields: [
      {
        name: "homeserver",
        label: "Homeserver URL",
        type: "text",
        required: true,
        placeholder: "https://matrix.org",
      },
      {
        name: "access_token",
        label: "Access Token",
        type: "password",
        required: true,
        placeholder: "syt_...",
      },
      {
        name: "room_id",
        label: "Room ID",
        type: "text",
        required: true,
        placeholder: "!abc123:matrix.org",
      },
      {
        name: "user_id",
        label: "User ID",
        type: "text",
        required: false,
        placeholder: "@bot:matrix.org",
      },
      { name: "device_id", label: "Device ID", type: "text", required: false },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
        placeholder: "@user:matrix.org",
      },
    ],
  },
  {
    channel_key: "email",
    display_name: "Email",
    description: "IMAP/SMTP email channel",
    fields: [
      {
        name: "imap_host",
        label: "IMAP Host",
        type: "text",
        required: true,
        placeholder: "imap.gmail.com",
      },
      {
        name: "imap_port",
        label: "IMAP Port",
        type: "number",
        required: false,
        default_value: 993,
      },
      {
        name: "imap_folder",
        label: "IMAP Folder",
        type: "text",
        required: false,
        default_value: "INBOX",
      },
      {
        name: "smtp_host",
        label: "SMTP Host",
        type: "text",
        required: true,
        placeholder: "smtp.gmail.com",
      },
      {
        name: "smtp_port",
        label: "SMTP Port",
        type: "number",
        required: false,
        default_value: 465,
      },
      {
        name: "smtp_tls",
        label: "SMTP TLS",
        type: "boolean",
        required: false,
        default_value: true,
      },
      {
        name: "username",
        label: "Username",
        type: "text",
        required: true,
        placeholder: "bot@example.com",
      },
      { name: "password", label: "Password", type: "password", required: true },
      {
        name: "from_address",
        label: "From Address",
        type: "text",
        required: true,
        placeholder: "bot@example.com",
      },
      {
        name: "idle_timeout_secs",
        label: "IDLE Timeout (s)",
        type: "number",
        required: false,
        default_value: 1740,
      },
      {
        name: "allowed_senders",
        label: "Allowed Senders",
        type: "string_array",
        required: false,
        placeholder: "user@example.com",
      },
      {
        name: "default_subject",
        label: "Default Subject",
        type: "text",
        required: false,
        default_value: "JhedaiClaw Message",
      },
    ],
  },
  {
    channel_key: "irc",
    display_name: "IRC",
    description: "Internet Relay Chat",
    fields: [
      {
        name: "server",
        label: "Server",
        type: "text",
        required: true,
        placeholder: "irc.libera.chat",
      },
      {
        name: "port",
        label: "Port",
        type: "number",
        required: false,
        default_value: 6697,
      },
      {
        name: "nickname",
        label: "Nickname",
        type: "text",
        required: true,
        placeholder: "jhedaiclaw",
      },
      { name: "username", label: "Username", type: "text", required: false },
      {
        name: "channels",
        label: "Channels",
        type: "string_array",
        required: false,
        placeholder: "#channel",
      },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
      },
      {
        name: "server_password",
        label: "Server Password",
        type: "password",
        required: false,
      },
      {
        name: "nickserv_password",
        label: "NickServ Password",
        type: "password",
        required: false,
      },
      {
        name: "sasl_password",
        label: "SASL Password",
        type: "password",
        required: false,
      },
      {
        name: "verify_tls",
        label: "Verify TLS",
        type: "boolean",
        required: false,
        default_value: true,
      },
    ],
  },
  {
    channel_key: "mattermost",
    display_name: "Mattermost",
    description: "Open-source Slack alternative",
    fields: [
      {
        name: "url",
        label: "Server URL",
        type: "text",
        required: true,
        placeholder: "https://mattermost.example.com",
      },
      {
        name: "bot_token",
        label: "Bot Token",
        type: "password",
        required: true,
      },
      {
        name: "channel_id",
        label: "Channel ID",
        type: "text",
        required: false,
      },
      {
        name: "allowed_users",
        label: "Allowed Users",
        type: "string_array",
        required: false,
      },
      {
        name: "thread_replies",
        label: "Thread Replies",
        type: "boolean",
        required: false,
      },
      {
        name: "mention_only",
        label: "Mention Only",
        type: "boolean",
        required: false,
      },
    ],
  },
  {
    channel_key: "wati",
    display_name: "WATI",
    description: "WhatsApp Business API via WATI",
    fields: [
      {
        name: "api_token",
        label: "API Token",
        type: "password",
        required: true,
      },
      {
        name: "api_url",
        label: "API URL",
        type: "text",
        required: false,
        default_value: "https://live-mt-server.wati.io",
      },
      { name: "tenant_id", label: "Tenant ID", type: "text", required: false },
      {
        name: "allowed_numbers",
        label: "Allowed Numbers",
        type: "string_array",
        required: false,
        placeholder: "+1234567890",
      },
    ],
  },
  {
    channel_key: "linq",
    display_name: "Linq",
    description: "Linq Partner API messaging",
    fields: [
      {
        name: "api_token",
        label: "API Token",
        type: "password",
        required: true,
      },
      {
        name: "from_phone",
        label: "From Phone",
        type: "text",
        required: true,
        placeholder: "+1234567890",
        help_text: "E.164 format.",
      },
      {
        name: "signing_secret",
        label: "Signing Secret",
        type: "password",
        required: false,
      },
      {
        name: "allowed_senders",
        label: "Allowed Senders",
        type: "string_array",
        required: false,
        placeholder: "+1234567890",
      },
    ],
  },
  {
    channel_key: "nostr",
    display_name: "Nostr",
    description: "Decentralized social protocol",
    fields: [
      {
        name: "private_key",
        label: "Private Key",
        type: "password",
        required: true,
        placeholder: "hex or nsec bech32",
        help_text: "Your Nostr private key.",
      },
      {
        name: "relays",
        label: "Relays",
        type: "string_array",
        required: false,
        placeholder: "wss://relay.damus.io",
        help_text: "Default: popular public relays.",
      },
      {
        name: "allowed_pubkeys",
        label: "Allowed Pubkeys",
        type: "string_array",
        required: false,
        placeholder: "hex pubkey",
      },
    ],
  },
  {
    channel_key: "webhook",
    display_name: "Webhook",
    description: "Generic HTTP webhook endpoint",
    fields: [
      {
        name: "port",
        label: "Port",
        type: "number",
        required: true,
        placeholder: "8080",
      },
      {
        name: "secret",
        label: "Secret",
        type: "password",
        required: false,
        help_text: "Shared secret for signature verification.",
      },
    ],
  },
  {
    channel_key: "clawdtalk",
    display_name: "ClawdTalk",
    description: "Voice channel via Telnyx SIP",
    fields: [
      {
        name: "api_key",
        label: "Telnyx API Key",
        type: "password",
        required: true,
      },
      {
        name: "connection_id",
        label: "SIP Connection ID",
        type: "text",
        required: true,
      },
      {
        name: "from_number",
        label: "From Number",
        type: "text",
        required: true,
        placeholder: "+1234567890",
        help_text: "E.164 format.",
      },
      {
        name: "allowed_destinations",
        label: "Allowed Destinations",
        type: "string_array",
        required: false,
        placeholder: "+1234567890",
      },
      {
        name: "webhook_secret",
        label: "Webhook Secret",
        type: "password",
        required: false,
      },
    ],
  },
];

export function getChannelSchema(key: string): ChannelSchema | undefined {
  return CHANNEL_SCHEMAS.find((s) => s.channel_key === key);
}

/** Map integration display name (from registry) to channel config key. */
export const INTEGRATION_TO_CHANNEL_KEY: Record<string, string> = {
  Telegram: "telegram",
  Discord: "discord",
  Slack: "slack",
  WhatsApp: "whatsapp",
  WATI: "wati",
  Signal: "signal",
  Matrix: "matrix",
  Email: "email",
  IRC: "irc",
  Mattermost: "mattermost",
  Linq: "linq",
  Nostr: "nostr",
  Webhooks: "webhook",
  ClawdTalk: "clawdtalk",
};
