//! Memory snapshot — export/import core memories as human-readable Markdown.

use anyhow::Result;
use chrono::Local;
use rusqlite::{Connection, OpenFlags, TransactionBehavior, params};
use std::fs;
use std::path::{Path, PathBuf};

use crate::sqlite::SqliteMemory;

/// Filename for the snapshot (lives at workspace root for Git visibility).
pub const SNAPSHOT_FILENAME: &str = "MEMORY_SNAPSHOT.md";

/// Header written at the top of every snapshot file.
const SNAPSHOT_HEADER: &str = "# 🧠 ZeroClaw Memory Snapshot\n\n\
    > Auto-generated by ZeroClaw. Do not edit manually unless you know what you're doing.\n\
    > This file is the \"soul\" of your agent — if `brain.db` is lost, start the agent\n\
    > in this workspace and it will auto-hydrate from this file.\n\n";

/// Export all `Core` memories from SQLite → `MEMORY_SNAPSHOT.md`.
/// Returns the number of entries exported.
pub fn export_snapshot(workspace_dir: &Path) -> Result<usize> {
    let db_path = workspace_dir.join("memory").join("brain.db");
    if !db_path.exists() {
        ::zeroclaw_log::record!(
            DEBUG,
            ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note),
            "snapshot export skipped: brain.db does not exist"
        );
        return Ok(0);
    }

    let conn = Connection::open(&db_path)?;
    conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;")?;

    let mut stmt = conn.prepare(
        "SELECT key, content, created_at, updated_at
         FROM memories
         WHERE category = 'core'
         ORDER BY updated_at DESC",
    )?;

    let rows: Vec<(String, String, String, String)> = stmt
        .query_map([], |row| {
            Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?))
        })?
        .collect::<rusqlite::Result<Vec<_>>>()?;

    if rows.is_empty() {
        ::zeroclaw_log::record!(
            DEBUG,
            ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note),
            "snapshot export: no core memories to export"
        );
        return Ok(0);
    }

    let mut output = String::with_capacity(rows.len() * 200);
    output.push_str(SNAPSHOT_HEADER);

    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    output.push_str(&format!("**Last exported:** {now}\n\n"));
    output.push_str(&format!(
        "**Total core memories:** {}\n\n---\n\n",
        rows.len()
    ));

    for (key, content, created_at, updated_at) in &rows {
        output.push_str(&format!("### 🔑 `{key}`\n\n"));
        output.push_str(content);
        output.push_str("\n\n");
        output.push_str(&format!(
            "*Created: {created_at} | Updated: {updated_at}*\n\n---\n\n"
        ));
    }

    let snapshot_path = snapshot_path(workspace_dir);
    fs::write(&snapshot_path, output)?;

    ::zeroclaw_log::record!(
        INFO,
        ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note),
        &format!(
            "📸 Memory snapshot exported: {} core memories → {}",
            rows.len(),
            snapshot_path.display().to_string()
        )
    );

    Ok(rows.len())
}

/// Import memories from `MEMORY_SNAPSHOT.md` into SQLite.
/// Called during cold-boot when `brain.db` doesn't exist but the snapshot does.
/// Returns the number of entries hydrated.
pub fn hydrate_from_snapshot(workspace_dir: &Path) -> Result<usize> {
    let snapshot = snapshot_path(workspace_dir);
    if !snapshot.exists() {
        return Ok(0);
    }

    let content = fs::read_to_string(&snapshot)?;
    let entries = parse_snapshot(&content);

    if entries.is_empty() {
        return Ok(0);
    }

    let db_path = workspace_dir.join("memory").join("brain.db");
    let mut conn = SqliteMemory::open_and_initialize(&db_path, None)?;
    let tx = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
    let existing_count: i64 =
        tx.query_row("SELECT COUNT(*) FROM memories", [], |row| row.get(0))?;
    if existing_count != 0 {
        return Ok(0);
    }
    let default_agent_id = zeroclaw_config::schema::v2::sqlite_ensure_default_agent_uuid(&tx)?;

    let now = Local::now().to_rfc3339();
    let mut hydrated = 0usize;

    for (key, content) in &entries {
        let id = uuid::Uuid::new_v4().to_string();
        let changed = tx.execute(
            "INSERT INTO memories (
                id, key, content, category, created_at, updated_at, agent_id
             ) VALUES (?1, ?2, ?3, 'core', ?4, ?5, ?6)
             ON CONFLICT(agent_id, key) DO NOTHING",
            params![id, key, content, now, now, default_agent_id],
        )?;
        hydrated += changed;
    }

    tx.commit()?;

    ::zeroclaw_log::record!(
        INFO,
        ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note),
        &format!(
            "🧬 Memory hydration complete: {} entries restored from {}",
            hydrated,
            snapshot.display().to_string()
        )
    );

    Ok(hydrated)
}

pub fn should_hydrate(workspace_dir: &Path) -> bool {
    let db_path = workspace_dir.join("memory").join("brain.db");
    let snapshot = snapshot_path(workspace_dir);

    if !snapshot.exists() {
        return false;
    }
    if !db_path.exists() {
        return true;
    }

    let conn = match Connection::open_with_flags(&db_path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .or_else(|_| Connection::open_with_flags(&db_path, OpenFlags::SQLITE_OPEN_READ_WRITE))
    {
        Ok(conn) => conn,
        Err(_) => {
            log_hydration_admission_failure();
            return false;
        }
    };

    let has_memories: rusqlite::Result<bool> = conn.query_row(
        "SELECT EXISTS(
             SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'memories'
         )",
        [],
        |row| row.get(0),
    );
    let has_memories = match has_memories {
        Ok(has_memories) => has_memories,
        Err(_) => {
            log_hydration_admission_failure();
            return false;
        }
    };
    if !has_memories {
        return true;
    }

    match conn.query_row("SELECT COUNT(*) FROM memories", [], |row| {
        row.get::<_, i64>(0)
    }) {
        Ok(count) => count == 0,
        Err(_) => {
            log_hydration_admission_failure();
            false
        }
    }
}

fn log_hydration_admission_failure() {
    ::zeroclaw_log::record!(
        WARN,
        ::zeroclaw_log::Event::new(module_path!(), ::zeroclaw_log::Action::Note)
            .with_outcome(::zeroclaw_log::EventOutcome::Unknown),
        "snapshot hydration admission inspection failed; skipping hydration"
    );
}

/// Path to the snapshot file.
fn snapshot_path(workspace_dir: &Path) -> PathBuf {
    workspace_dir.join(SNAPSHOT_FILENAME)
}

/// Parse the structured markdown snapshot back into (key, content) pairs.
fn parse_snapshot(input: &str) -> Vec<(String, String)> {
    let mut entries = Vec::new();
    let mut current_key: Option<String> = None;
    let mut current_content = String::new();

    for line in input.lines() {
        let trimmed = line.trim();

        // Match: ### 🔑 `key_name`
        if trimmed.starts_with("### 🔑 `") && trimmed.ends_with('`') {
            // Save previous entry
            if let Some(key) = current_key.take() {
                let content = current_content.trim().to_string();
                if !content.is_empty() {
                    entries.push((key, content));
                }
            }

            // Extract new key
            let key = trimmed
                .strip_prefix("### 🔑 `")
                .and_then(|s| s.strip_suffix('`'))
                .unwrap_or("")
                .to_string();

            if !key.is_empty() {
                current_key = Some(key);
                current_content = String::new();
            }
        } else if current_key.is_some() {
            // Skip metadata lines and separators
            if trimmed.starts_with("*Created:") || trimmed == "---" {
                continue;
            }
            // Accumulate content
            if !current_content.is_empty() || !trimmed.is_empty() {
                if !current_content.is_empty() {
                    current_content.push('\n');
                }
                current_content.push_str(line);
            }
        }
    }

    // Don't forget the last entry
    if let Some(key) = current_key {
        let content = current_content.trim().to_string();
        if !content.is_empty() {
            entries.push((key, content));
        }
    }

    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn parse_snapshot_basic() {
        let input = r#"# 🧠 ZeroClaw Memory Snapshot

> Auto-generated by ZeroClaw.

**Last exported:** 2025-01-15 14:30:00

**Total core memories:** 2

---

### 🔑 `identity`

I am ZeroClaw, a self-preserving AI agent.

*Created: 2025-01-15 | Updated: 2025-01-15*

---

### 🔑 `preference_lang`

The user prefers Rust for systems programming.

*Created: 2025-01-14 | Updated: 2025-01-15*

---
"#;

        let entries = parse_snapshot(input);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].0, "identity");
        assert!(entries[0].1.contains("self-preserving"));
        assert_eq!(entries[1].0, "preference_lang");
        assert!(entries[1].1.contains("Rust"));
    }

    #[test]
    fn parse_snapshot_empty() {
        let input = "# 🧠 ZeroClaw Memory Snapshot\n\n> Nothing here.\n";
        let entries = parse_snapshot(input);
        assert!(entries.is_empty());
    }

    #[test]
    fn parse_snapshot_multiline_content() {
        let input = r#"### 🔑 `rules`

Rule 1: Always be helpful.
Rule 2: Never lie.
Rule 3: Protect the user.

*Created: 2025-01-15 | Updated: 2025-01-15*

---
"#;

        let entries = parse_snapshot(input);
        assert_eq!(entries.len(), 1);
        assert!(entries[0].1.contains("Rule 1"));
        assert!(entries[0].1.contains("Rule 3"));
    }

    #[test]
    fn export_no_db_returns_zero() {
        let tmp = TempDir::new().unwrap();
        let count = export_snapshot(tmp.path()).unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn export_decode_failure_does_not_replace_snapshot() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        fs::write(&snapshot, "existing snapshot").unwrap();

        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "CREATE TABLE memories (
                id TEXT PRIMARY KEY,
                key TEXT NOT NULL,
                content TEXT NOT NULL,
                category TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
             );
             INSERT INTO memories VALUES ('id', 'broken', X'00', 'core', 'created', 'updated');",
        )
        .unwrap();
        drop(conn);

        assert!(export_snapshot(workspace).is_err());
        assert_eq!(fs::read_to_string(snapshot).unwrap(), "existing snapshot");
    }

    #[test]
    fn hydrate_uses_canonical_schema_default_agent_and_fts() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        fs::write(
            workspace.join(SNAPSHOT_FILENAME),
            "### 🔑 `identity`\n\nI am a test agent\n",
        )
        .unwrap();

        assert_eq!(hydrate_from_snapshot(workspace).unwrap(), 1);
        let conn = Connection::open(workspace.join("memory").join("brain.db")).unwrap();
        let agent_alias: String = conn
            .query_row(
                "SELECT a.alias FROM memories m JOIN agents a ON a.id = m.agent_id",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(agent_alias, "default");

        let agent_id_not_null: i64 = conn
            .query_row(
                "SELECT [notnull] FROM pragma_table_info('memories') WHERE name = 'agent_id'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(agent_id_not_null, 1);

        let unique_agent_key = {
            let indexes: Vec<String> = {
                let mut stmt = conn.prepare("PRAGMA index_list(memories)").unwrap();
                stmt.query_map([], |row| {
                    let unique: i64 = row.get(2)?;
                    let name: String = row.get(1)?;
                    Ok((unique != 0, name))
                })
                .unwrap()
                .filter_map(|result| result.ok())
                .filter(|(unique, _)| *unique)
                .map(|(_, name)| name)
                .collect()
            };
            indexes.into_iter().any(|index_name| {
                let mut info = conn
                    .prepare("SELECT name FROM pragma_index_info(?1) ORDER BY seqno")
                    .unwrap();
                let columns: Vec<String> = info
                    .query_map([index_name], |row| row.get(0))
                    .unwrap()
                    .collect::<rusqlite::Result<Vec<_>>>()
                    .unwrap();
                columns.len() == 2
                    && columns.iter().any(|column| column == "agent_id")
                    && columns.iter().any(|column| column == "key")
            })
        };
        assert!(unique_agent_key);

        let (memory_rowid, fts_rowid): (i64, i64) = conn
            .query_row(
                "SELECT m.rowid, f.rowid FROM memories m JOIN memories_fts f ON f.rowid = m.rowid",
                [],
                |row| Ok((row.get(0)?, row.get(1)?)),
            )
            .unwrap();
        assert_eq!(memory_rowid, fts_rowid);
        let found: String = conn
            .query_row(
                "SELECT key FROM memories_fts WHERE memories_fts MATCH 'agent'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(found, "identity");
    }

    #[test]
    fn hydrate_keeps_first_duplicate_key() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        fs::write(
            workspace.join(SNAPSHOT_FILENAME),
            "### 🔑 `first`\n\nfirst value\n\n### 🔑 `first`\n\nduplicate value\n",
        )
        .unwrap();

        assert_eq!(hydrate_from_snapshot(workspace).unwrap(), 1);
        let conn = Connection::open(workspace.join("memory").join("brain.db")).unwrap();
        let content: String = conn
            .query_row(
                "SELECT content FROM memories WHERE key = 'first'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(content, "first value");
        let fts_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM memories_fts", [], |row| row.get(0))
            .unwrap();
        assert_eq!(fts_count, 1);
    }

    #[test]
    fn hydrate_rolls_back_entire_batch_on_insert_failure() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        fs::write(
            workspace.join(SNAPSHOT_FILENAME),
            "### 🔑 `first`\n\nfirst value\n\n### 🔑 `second`\n\nsecond value\n",
        )
        .unwrap();

        let db_path = workspace.join("memory").join("brain.db");
        let conn = SqliteMemory::open_and_initialize(&db_path, None).unwrap();
        conn.execute_batch(
            "CREATE TRIGGER reject_second_snapshot_entry
             BEFORE INSERT ON memories
             WHEN NEW.key = 'second'
             BEGIN
                 SELECT RAISE(ABORT, 'injected snapshot insert failure');
             END;",
        )
        .unwrap();
        drop(conn);

        assert!(hydrate_from_snapshot(workspace).is_err());
        let conn = Connection::open(db_path).unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM memories", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, 0);
        let fts_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM memories_fts", [], |row| row.get(0))
            .unwrap();
        assert_eq!(fts_count, 0);
    }

    #[test]
    fn should_hydrate_inspects_schema_and_wal_rows() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        fs::write(&snapshot, "### 🔑 `test`\n\nHello\n").unwrap();
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");

        // A valid database without memories is eligible.
        Connection::open(&db_path)
            .unwrap()
            .execute("CREATE TABLE unrelated (value TEXT)", [])
            .unwrap();
        assert!(should_hydrate(workspace));

        // An empty memories table is eligible.
        let conn = Connection::open(&db_path).unwrap();
        conn.execute("CREATE TABLE memories (key TEXT)", [])
            .unwrap();
        drop(conn);
        assert!(should_hydrate(workspace));

        // A committed WAL row is visible to read-only admission.
        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA wal_autocheckpoint = 0;")
            .unwrap();
        conn.execute("INSERT INTO memories VALUES ('populated')", [])
            .unwrap();
        assert!(!should_hydrate(workspace));
        drop(conn);

        // A corrupt existing database fails closed rather than hydrating.
        fs::remove_file(&db_path).unwrap();
        fs::write(&db_path, "not a sqlite database").unwrap();
        assert!(!should_hydrate(workspace));
    }

    #[test]
    fn should_hydrate_opens_closed_empty_wal_without_sidecars() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        fs::write(
            workspace.join(SNAPSHOT_FILENAME),
            "### 🔑 `test`\n\nHello\n",
        )
        .unwrap();
        let db_path = workspace.join("memory").join("brain.db");

        let conn = SqliteMemory::open_and_initialize(&db_path, None).unwrap();
        drop(conn);
        for sidecar in [
            db_path.with_extension("db-wal"),
            db_path.with_extension("db-shm"),
        ] {
            if sidecar.exists() {
                fs::remove_file(&sidecar).unwrap();
            }
            assert!(!sidecar.exists());
        }

        assert!(should_hydrate(workspace));
    }

    #[test]
    fn hydrate_skips_snapshot_when_live_row_arrives_after_admission() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();
        fs::write(
            workspace.join(SNAPSHOT_FILENAME),
            "### 🔑 `snapshot`\n\nsnapshot value\n",
        )
        .unwrap();
        let db_path = workspace.join("memory").join("brain.db");
        let conn = SqliteMemory::open_and_initialize(&db_path, None).unwrap();
        drop(conn);

        assert!(should_hydrate(workspace));

        let conn = SqliteMemory::open_and_initialize(&db_path, None).unwrap();
        let default_agent_id =
            zeroclaw_config::schema::v2::sqlite_ensure_default_agent_uuid(&conn).unwrap();
        let now = Local::now().to_rfc3339();
        conn.execute(
            "INSERT INTO memories (
                id, key, content, category, created_at, updated_at, agent_id
             ) VALUES (?1, 'live', 'live value', 'core', ?2, ?2, ?3)",
            params![uuid::Uuid::new_v4().to_string(), now, default_agent_id],
        )
        .unwrap();
        drop(conn);

        assert_eq!(hydrate_from_snapshot(workspace).unwrap(), 0);
        let conn = Connection::open(&db_path).unwrap();
        let rows: Vec<(String, String)> = conn
            .prepare("SELECT key, content FROM memories ORDER BY key")
            .unwrap()
            .query_map([], |row| Ok((row.get(0)?, row.get(1)?)))
            .unwrap()
            .collect::<rusqlite::Result<Vec<_>>>()
            .unwrap();
        assert_eq!(rows, vec![("live".to_string(), "live value".to_string())]);
    }

    #[test]
    fn export_and_hydrate_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();

        // Create a brain.db manually with some core memories
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");

        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "PRAGMA journal_mode = WAL;
             CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                key TEXT NOT NULL UNIQUE,
                content TEXT NOT NULL,
                category TEXT NOT NULL DEFAULT 'core',
                embedding BLOB,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
             );
             CREATE INDEX IF NOT EXISTS idx_mem_key ON memories(key);",
        )
        .unwrap();

        let now = Local::now().to_rfc3339();
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id1', 'identity', 'I am a test agent', 'core', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id2', 'preference', 'User likes Rust', 'core', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        // Non-core entry (should NOT be exported)
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id3', 'conv1', 'Random convo', 'conversation', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        drop(conn);

        // Export snapshot
        let exported = export_snapshot(workspace).unwrap();
        assert_eq!(exported, 2, "Should export only core memories");

        // Verify the file exists and is readable
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        assert!(snapshot.exists());
        let content = fs::read_to_string(&snapshot).unwrap();
        assert!(content.contains("identity"));
        assert!(content.contains("I am a test agent"));
        assert!(content.contains("preference"));
        assert!(!content.contains("Random convo"));

        // Simulate catastrophic failure: delete brain.db
        fs::remove_file(&db_path).unwrap();
        assert!(!db_path.exists());

        // Verify should_hydrate detects the scenario
        assert!(should_hydrate(workspace));

        // Hydrate from snapshot
        let hydrated = hydrate_from_snapshot(workspace).unwrap();
        assert_eq!(hydrated, 2, "Should hydrate both core memories");

        // Verify brain.db was recreated
        assert!(db_path.exists());

        // Verify the data is actually in the new database
        let conn = Connection::open(&db_path).unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM memories", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, 2);

        let identity: String = conn
            .query_row(
                "SELECT content FROM memories WHERE key = 'identity'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(identity, "I am a test agent");
    }

    #[test]
    fn should_hydrate_only_when_needed() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();

        // No DB, no snapshot → false
        assert!(!should_hydrate(workspace));

        // Create snapshot but no DB → true
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        fs::write(&snapshot, "### 🔑 `test`\n\nHello\n").unwrap();
        assert!(should_hydrate(workspace));

        // Create a real DB → false
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");
        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                key TEXT NOT NULL UNIQUE,
                content TEXT NOT NULL,
                category TEXT NOT NULL DEFAULT 'core',
                embedding BLOB,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
             );
             INSERT INTO memories VALUES('x','x','x','core',NULL,'2025-01-01','2025-01-01');",
        )
        .unwrap();
        drop(conn);
        assert!(!should_hydrate(workspace));
    }

    #[test]
    fn hydrate_no_snapshot_returns_zero() {
        let tmp = TempDir::new().unwrap();
        let count = hydrate_from_snapshot(tmp.path()).unwrap();
        assert_eq!(count, 0);
    }
}
