//! Generate the feature-and-support matrix snippets for the mdBook from the
//! canonical code registries: the channel inventory, the model-provider slots,
//! and the default tool set. The registries are the single source of truth; the
//! docs render whatever they carry so a channel/provider/tool add reflows the

use anyhow::Result;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::sync::Arc;

use serde::Deserialize;
use zeroclaw_config::schema::ChannelsConfig;
use zeroclaw_runtime::tools::default_tools;

const SNIPPET_DIR: &str = "docs/book/src/_snippets";
const PARITY_FILE: &str = "docs/book/feature-matrix-parity.toml";

const HEADER: &str = "<!--\n  GENERATED by `cargo xtask mdbook` from the code registries (channel\n  inventory, model-provider slots, default tools) + feature-matrix-parity.toml.\n  Derived + gitignored: do not edit, do not commit. Regenerated on every docs\n  build.\n-->\n\n";

#[derive(Debug, Deserialize)]
struct Parity {
    #[serde(default)]
    channels: BTreeMap<String, Column>,
    #[serde(default)]
    providers: BTreeMap<String, Column>,
    #[serde(default)]
    tools: BTreeMap<String, Column>,
}

#[derive(Debug, Deserialize)]
struct Column {
    openclaw: Status,
    hermes: Status,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
enum Status {
    Supported,
    Partial,
    Experimental,
    Planned,
    None,
    Unknown,
}

impl Status {
    fn cell(self) -> &'static str {
        match self {
            Status::Supported => "✅",
            Status::Partial => "🟡",
            Status::Experimental => "🧪",
            Status::Planned => "📋",
            Status::None => "❌",
            Status::Unknown => "❓",
        }
    }
}

struct Row {
    label: String,
    zeroclaw: Status,
    openclaw: Status,
    hermes: Status,
}

pub fn run(root: &Path) -> Result<()> {
    let parity = load_parity(root)?;
    let dir = root.join(SNIPPET_DIR);
    std::fs::create_dir_all(&dir)?;

    std::fs::write(
        dir.join("feature-matrix-channels.md"),
        table("Channel", &channels_rows(&parity)?),
    )?;
    std::fs::write(
        dir.join("feature-matrix-providers.md"),
        table("Provider slot", &providers_rows(&parity)?),
    )?;
    std::fs::write(
        dir.join("feature-matrix-tools.md"),
        table("Tool", &tools_rows(&parity)?),
    )?;

    eprintln!("==> Generated feature-matrix snippets from code registries");
    Ok(())
}

fn load_parity(root: &Path) -> Result<Parity> {
    let path = root.join(PARITY_FILE);
    let raw = std::fs::read_to_string(&path)
        .map_err(|e| anyhow::Error::msg(format!("{}: {e}", path.display())))?;
    toml::from_str(&raw).map_err(|e| anyhow::Error::msg(format!("{PARITY_FILE}: {e}")))
}

fn table(header: &str, rows: &[Row]) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "| {header} | ZeroClaw | OpenClaw | Hermes |");
    out.push_str("|---|---|---|---|\n");
    for r in rows {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            r.label,
            r.zeroclaw.cell(),
            r.openclaw.cell(),
            r.hermes.cell()
        );
    }
    out
}

fn channels_rows(parity: &Parity) -> Result<Vec<Row>> {
    let cfg = ChannelsConfig::default();
    let mut rows = Vec::new();
    let mut walked = std::collections::BTreeSet::new();
    for info in cfg.channels() {
        walked.insert(info.kind.to_string());
        let (openclaw, hermes) = external_cells(parity.channels.get(info.kind));
        rows.push(Row {
            label: info.name.to_string(),
            zeroclaw: Status::Supported,
            openclaw,
            hermes,
        });
    }
    assert_no_stale("channels", &walked, &parity.channels)?;
    Ok(rows)
}

fn providers_rows(parity: &Parity) -> Result<Vec<Row>> {
    let mut rows = Vec::new();
    let mut walked = std::collections::BTreeSet::new();
    for slot in zeroclaw_providers::canonical_model_provider_slots() {
        walked.insert(slot.to_string());
        let (openclaw, hermes) = external_cells(parity.providers.get(slot));
        rows.push(Row {
            label: format!("`{slot}`"),
            zeroclaw: Status::Supported,
            openclaw,
            hermes,
        });
    }
    assert_no_stale("providers", &walked, &parity.providers)?;
    Ok(rows)
}

fn tools_rows(parity: &Parity) -> Result<Vec<Row>> {
    let security = Arc::new(zeroclaw_config::policy::SecurityPolicy::default());
    let mut rows = Vec::new();
    let mut walked = std::collections::BTreeSet::new();
    for tool in default_tools(security) {
        let name = tool.name().to_string();
        walked.insert(name.clone());
        let (openclaw, hermes) = external_cells(parity.tools.get(&name));
        rows.push(Row {
            label: format!("`{name}`"),
            zeroclaw: Status::Supported,
            openclaw,
            hermes,
        });
    }
    assert_no_stale("tools", &walked, &parity.tools)?;
    Ok(rows)
}

fn external_cells(col: Option<&Column>) -> (Status, Status) {
    match col {
        Some(c) => (c.openclaw, c.hermes),
        None => (Status::Unknown, Status::Unknown),
    }
}

fn assert_no_stale(
    section: &str,
    walked: &std::collections::BTreeSet<String>,
    parity: &BTreeMap<String, Column>,
) -> Result<()> {
    let stale: Vec<&str> = parity
        .keys()
        .filter(|k| !walked.contains(*k))
        .map(String::as_str)
        .collect();
    if !stale.is_empty() {
        anyhow::bail!(
            "{PARITY_FILE}: [{section}] has entries the source walk does not produce: {}",
            stale.join(", ")
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> std::path::PathBuf {
        crate::util::repo_root()
    }

    #[test]
    fn parity_join_produces_rows_without_stale_keys() {
        let parity = load_parity(&root()).unwrap();
        channels_rows(&parity).unwrap();
        providers_rows(&parity).unwrap();
        tools_rows(&parity).unwrap();
    }

    #[test]
    fn channel_column_is_all_supported_from_walk() {
        let parity = load_parity(&root()).unwrap();
        for r in channels_rows(&parity).unwrap() {
            assert_eq!(r.zeroclaw, Status::Supported);
        }
    }
}
