//! Generate the hardware reference snippets for the mdBook from canonical
//! source: the board registry, transport kinds, the tool catalog, and the
//! release target matrix. The registry is the single source of truth; the docs
//! render whatever it carries so a board add, transport rename, tool rename, or
//! target change reflows the rendered tables on the next build with no hand
//! edit.
//!
//! Outputs (gitignored, derived — `{{#include}}`d at build time):
//!   docs/book/src/_snippets/hardware-boards.md
//!   docs/book/src/_snippets/hardware-transports.md
//!   docs/book/src/_snippets/hardware-tools-base.md
//!   docs/book/src/_snippets/hardware-tools-aardvark.md
//!   docs/book/src/_snippets/hardware-release-targets.md

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use zeroclaw_hardware::catalog::{AARDVARK_TOOLS, BASE_TOOLS};
use zeroclaw_hardware::registry::known_boards;
use zeroclaw_hardware::transport::TransportKind;

const SNIPPET_DIR: &str = "docs/book/src/_snippets";

const HEADER: &str = "<!--\n  GENERATED by `cargo xtask mdbook` from canonical hardware source\n  (registry.rs, transport.rs, catalog.rs, release workflow). Derived +\n  gitignored: do not edit, do not commit. Regenerated on every docs build.\n-->\n\n";

/// Release targets that ship a prebuilt binary. Mirrors the `target:` matrix in
/// `.github/workflows/release-stable-manual.yml`; the workflow is the canonical
/// source. Parsed from the workflow at generation time so the two cannot drift.
const RELEASE_WORKFLOW: &str = ".github/workflows/release-stable-manual.yml";

pub fn run(root: &Path) -> Result<()> {
    let dir = root.join(SNIPPET_DIR);
    std::fs::create_dir_all(&dir)?;

    std::fs::write(dir.join("hardware-boards.md"), render_boards())?;
    std::fs::write(dir.join("hardware-transports.md"), render_transports())?;
    std::fs::write(
        dir.join("hardware-tools-base.md"),
        render_tool_list(BASE_TOOLS),
    )?;
    std::fs::write(
        dir.join("hardware-tools-aardvark.md"),
        render_tool_list(AARDVARK_TOOLS),
    )?;
    std::fs::write(
        dir.join("hardware-release-targets.md"),
        render_release_targets(root)?,
    )?;

    println!("==> Generated hardware reference snippets from registry + catalog");
    Ok(())
}

fn render_boards() -> String {
    let mut out = String::from(HEADER);
    out.push_str("| Board | Architecture | USB VID:PID |\n|---|---|---|\n");
    for b in known_boards() {
        let arch = b.architecture.unwrap_or("—");
        let _ = writeln!(
            out,
            "| `{}` | {} | `{:#06x}`:`{:#06x}` |",
            b.name, arch, b.vid, b.pid
        );
    }
    out
}

fn render_transports() -> String {
    let mut out = String::from(HEADER);
    out.push_str("| Transport | Description |\n|---|---|\n");
    for (kind, desc) in [
        (
            TransportKind::Serial,
            "Newline-delimited JSON over USB CDC serial",
        ),
        (TransportKind::Swd, "SWD debug probe (probe-rs)"),
        (TransportKind::Uf2, "UF2 mass-storage firmware flashing"),
        (
            TransportKind::Native,
            "Direct Linux GPIO/I2C/SPI (rppal, sysfs)",
        ),
        (
            TransportKind::Aardvark,
            "Total Phase Aardvark USB adapter (I2C/SPI/GPIO)",
        ),
    ] {
        let _ = writeln!(out, "| `{kind}` | {desc} |");
    }
    out
}

fn render_tool_list(tools: &[&str]) -> String {
    let mut out = String::from(HEADER);
    for name in tools {
        let _ = writeln!(out, "- `{name}`");
    }
    out
}

fn render_release_targets(root: &Path) -> Result<String> {
    let workflow = std::fs::read_to_string(root.join(RELEASE_WORKFLOW)).map_err(|e| {
        anyhow::Error::msg(format!(
            "release workflow missing at {RELEASE_WORKFLOW}: {e}. It is the canonical \
             source for the prebuilt-binary target matrix."
        ))
    })?;
    let mut targets: Vec<String> = workflow
        .lines()
        .filter_map(|l| l.trim().strip_prefix("target:"))
        .map(|t| t.trim().to_string())
        .collect();
    targets.sort_unstable();
    targets.dedup();
    if targets.is_empty() {
        anyhow::bail!("no `target:` entries parsed from {RELEASE_WORKFLOW}");
    }
    let mut out = String::from(HEADER);
    for t in targets {
        let _ = writeln!(out, "- `{t}`");
    }
    Ok(out)
}
