name: Bug Report
description: Report a reproducible defect in ZeroClaw
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please provide a minimal reproducible case so maintainers can triage quickly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the problem.
      placeholder: zeroclaw daemon exits immediately when ...
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: What is happening now?
      placeholder: The process exits with ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
      placeholder: The daemon should stay alive and ...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide exact commands/config.
      placeholder: |
        1. zeroclaw onboard --interactive
        2. zeroclaw daemon
        3. Observe crash in logs
      render: bash
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      description: Paste relevant logs (redact secrets).
      render: text
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: ZeroClaw version
      placeholder: v0.1.0 / commit SHA
    validations:
      required: true

  - type: input
    id: rust
    attributes:
      label: Rust version
      placeholder: rustc 1.xx.x
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 24.04 / macOS 15 / Windows 11
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Regression?
      options:
        - Unknown
        - Yes, it worked before
        - No, first-time setup
    validations:
      required: true
