apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: todolist-certificate-production
  namespace: istio-system
spec:
  issuerRef:
    name: ci-istio-letsencrypt-cloudflare-prod
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: todolist-certificate-secret-production
  dnsNames:
    - todolist.coffee-anon.com
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
