[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-static", "-C", "link-arg=-Wl,-z,stack-size=8388608"]

# Android targets (NDK toolchain)
[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
rustflags = ["-C", "link-arg=-Wl,-z,stack-size=8388608"]

# riscv64gc-unknown-linux-musl target, produces a static binary with musl, but requires a custom linker and flags
[target.riscv64gc-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
]
linker = "riscv64-linux-musl-gcc"

