// Guest-side WIT bindings, generated by `wit_bindgen::generate!`. One
// module per world, gated by the matching Cargo feature plus the
// `plugins-wit-v0` WIT-major-version feature (same feature name the host's
// `zeroclaw-plugins` crate uses). Never hand-edit; these are regenerated
// from `wit/v0/*.wit` on every build.
//
// Unlike the host's three simultaneous `wasmtime::component::bindgen!`
// modules in `zeroclaw-plugins/src/component/v0/bindings.rs`, these
// `generate!` calls cannot all be active at once: worlds that share an
// identical exported interface (every world here exports `plugin-info`)
// produce a `#[macro_export]`-style cabi shim named after that interface,
// which collides at the crate root regardless of `mod` nesting once two
// such worlds are both generated into one crate. This is fine — a plugin
// component implements exactly one world anyway — but it means no build of
// this crate may enable more than one of `tool`/`memory`/`channel` at a
// time. The crate's own dev-dependent test targets enforce this via
// `required-features` in `Cargo.toml`.

#[cfg(all(feature = "tool", feature = "plugins-wit-v0"))]
pub mod tool {
    wit_bindgen::generate!({
        world: "tool-plugin",
        path: "../../wit/v0",
        features: ["plugins-wit-v0"],
        pub_export_macro: true,
    });
}

#[cfg(all(feature = "memory", feature = "plugins-wit-v0"))]
pub mod memory {
    wit_bindgen::generate!({
        world: "memory-plugin",
        path: "../../wit/v0",
        features: ["plugins-wit-v0"],
        pub_export_macro: true,
    });
}
