// Guest-side WIT bindings, generated by `wit_bindgen::generate!`. One
// private module per world, gated by the matching Cargo feature plus the
// `plugins-wit-v0` WIT-major-version feature (same feature name the host's
// `zeroclaw-plugins` crate uses), mirroring the host's per-world
// `wasmtime::component::bindgen!` modules in
// `zeroclaw-plugins/src/component/v0/bindings.rs`. Never hand-edit; these
// are regenerated from `wit/v0/*.wit` on every build.

#[cfg(all(feature = "tool", feature = "plugins-wit-v0"))]
pub mod tool {
    wit_bindgen::generate!({
        world: "tool-plugin",
        path: "../../wit/v0",
        features: ["plugins-wit-v0"],
        pub_export_macro: true,
    });
}
