apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeroclaw-data
  namespace: zeroclaw-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
