apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeroclaw-sam-tools
  namespace: zeroclaw-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
