#!/usr/bin/env bash
#
# mtls-relay-testbed.sh - stand up a self-contained mTLS WSS testbed and prove
# both reach paths a `zerocode` client can use against a running daemon:
#
#   1. DIRECT     zerocode --connect wss://127.0.0.1:<wss>           (mutual TLS)
#   2. VIA RELAY  zerocode --connect wss://127.0.0.1:<wss> \
#                          --relay 127.0.0.1:<relay> --relay-node <id>
#
# It builds the three binaries (zeroclaw, zerocode, zerorelay), creates an
# isolated config dir with [wss] + [relay] enabled, boots a relay and a daemon,
# issues a client certificate from the daemon's auto-generated CA, and then
# self-verifies BOTH paths before handing you live processes plus the exact
# zerocode commands to run by hand.
#
# Self-checks (hard failures, exit non-zero):
#   - direct mTLS handshake SUCCEEDS with the client cert (TLS 1.3, Verify OK)
#   - direct mTLS handshake is REJECTED without a client cert (mandatory mTLS)
#   - the same mutual-TLS handshake completes end-to-end THROUGH the blind relay
#
# Nothing here touches a real deployment: it runs on test ports under a scratch
# dir, and the mTLS/relay code is inert in normal daemon config (no [wss]).
#
# Usage:
#   scripts/dev/mtls-relay-testbed.sh [--check-only] [--skip-build] [-h]
#
# Environment overrides:
#   ZC_TESTBED_DIR    workspace dir         (default: ${TMPDIR:-/tmp}/zc-mtls-testbed)
#   ZC_WSS_PORT       daemon WSS port       (default: 9799)
#   ZC_RELAY_PORT     relay listen port     (default: 8459)
#   ZC_NODE_ID        relay node-id         (default: testbed-daemon)
#   ZC_PROFILE        cargo profile         (release|debug, default: release)
#
# Flags:
#   --check-only      run both self-checks, tear everything down, exit (CI smoke)
#   --skip-build      reuse already-built binaries (same as ZC_TESTBED_SKIP_BUILD=1)
#   -h, --help        this help

set -euo pipefail

# --- locate the repo root (this script lives in scripts/dev/) ----------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- options -----------------------------------------------------------------
CHECK_ONLY=0
SKIP_BUILD="${ZC_TESTBED_SKIP_BUILD:-0}"
for arg in "$@"; do
  case "$arg" in
    --check-only) CHECK_ONLY=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    -h|--help) sed -n '2,46p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $arg (try --help)" >&2; exit 2 ;;
  esac
done

TB="${ZC_TESTBED_DIR:-${TMPDIR:-/tmp}/zc-mtls-testbed}"
WSS_PORT="${ZC_WSS_PORT:-9799}"
RELAY_PORT="${ZC_RELAY_PORT:-8459}"
NODE_ID="${ZC_NODE_ID:-testbed-daemon}"
PROFILE="${ZC_PROFILE:-release}"
RELAY_TOKEN="testbed-token"

case "$PROFILE" in
  release) BIN_DIR="$REPO_ROOT/target/release"; CARGO_PROFILE_FLAG="--release" ;;
  debug)   BIN_DIR="$REPO_ROOT/target/debug";   CARGO_PROFILE_FLAG="" ;;
  *) echo "ZC_PROFILE must be 'release' or 'debug' (got '$PROFILE')" >&2; exit 2 ;;
esac
ZEROCLAW="$BIN_DIR/zeroclaw"
ZEROCODE="$BIN_DIR/zerocode"
ZERORELAY="$BIN_DIR/zerorelay"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ok\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mFAIL\033[0m %s\n' "$*" >&2; exit 1; }

# --- teardown ----------------------------------------------------------------
DAEMON_PID=""
RELAY_PID=""
cleanup() {
  [ -n "$DAEMON_PID" ] && kill "$DAEMON_PID" 2>/dev/null || true
  [ -n "$RELAY_PID" ]  && kill "$RELAY_PID"  2>/dev/null || true
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# --- 1. build ----------------------------------------------------------------
if [ "$SKIP_BUILD" = "1" ]; then
  say "skipping build (reusing binaries in $BIN_DIR)"
  for b in "$ZEROCLAW" "$ZEROCODE" "$ZERORELAY"; do
    [ -x "$b" ] || die "missing binary $b (drop --skip-build to build it)"
  done
else
  say "building zeroclaw, zerocode, zerorelay ($PROFILE) ..."
  ( cd "$REPO_ROOT" && cargo build $CARGO_PROFILE_FLAG \
      --features channels-full \
      -p zeroclawlabs -p zerocode -p zerorelay ) \
    || die "build failed"
fi
ok "binaries ready in $BIN_DIR"

# --- 2. isolated workspace + config -----------------------------------------
say "preparing workspace at $TB"
rm -rf "$TB"
mkdir -p "$TB"
cat > "$TB/config.toml" <<TOML
# Generated by mtls-relay-testbed.sh - isolated mTLS WSS testbed.
default_provider = "ollama"
default_model = "llama3.2"

[gateway]
enabled = false

# Mutually authenticated remote control plane. CA + server cert are
# auto-generated under <config_dir>/data/tls on first boot.
[wss]
enabled = true
bind = "127.0.0.1"
port = $WSS_PORT

# Outbound bridge to the nominated relay so a client can reach this daemon by
# node-id without a direct route. Inert unless [wss] is also enabled.
[relay]
enabled = true
url = "127.0.0.1:$RELAY_PORT"
node_id = "$NODE_ID"
token = "$RELAY_TOKEN"
TOML
ok "wrote $TB/config.toml (wss :$WSS_PORT, relay :$RELAY_PORT, node '$NODE_ID')"

CA="$TB/data/tls/ca.crt"
CLIENT_DIR="$TB/clientcerts"
CLIENT_CRT="$CLIENT_DIR/client-zerocode.crt"
CLIENT_KEY="$CLIENT_DIR/client-zerocode.key"

# --- 3. start the relay (open admission) -------------------------------------
say "starting zerorelay on 127.0.0.1:$RELAY_PORT (open admission)"
"$ZERORELAY" --bind "127.0.0.1:$RELAY_PORT" --registration-mode open \
  > "$TB/relay.log" 2>&1 &
RELAY_PID=$!
for _ in $(seq 1 40); do
  ss -ltn 2>/dev/null | grep -q ":$RELAY_PORT" && break
  kill -0 "$RELAY_PID" 2>/dev/null || die "relay died on startup (see $TB/relay.log)"
  sleep 0.25
done
ss -ltn 2>/dev/null | grep -q ":$RELAY_PORT" || die "relay never bound :$RELAY_PORT"
ok "relay listening (pid $RELAY_PID)"

# --- 4. start the daemon -----------------------------------------------------
say "starting daemon (auto-generates CA, binds WSS, registers with relay)"
ZEROCLAW_CONFIG_DIR="$TB" "$ZEROCLAW" daemon > "$TB/daemon.log" 2>&1 &
DAEMON_PID=$!
for _ in $(seq 1 80); do
  [ -f "$CA" ] && ss -ltn 2>/dev/null | grep -q ":$WSS_PORT" && break
  kill -0 "$DAEMON_PID" 2>/dev/null || die "daemon died on startup (see $TB/daemon.log)"
  sleep 0.25
done
[ -f "$CA" ] || die "CA was not generated at $CA"
ss -ltn 2>/dev/null | grep -q ":$WSS_PORT" || die "daemon never bound WSS :$WSS_PORT"
ok "daemon up (pid $DAEMON_PID), CA at $CA, WSS on :$WSS_PORT"

# --- 5. issue a client certificate -------------------------------------------
say "issuing a client certificate from the daemon CA"
ZEROCLAW_CONFIG_DIR="$TB" "$ZEROCLAW" security issue-client-cert \
  --name zerocode --out-dir "$CLIENT_DIR" --force > "$TB/issue.log" 2>&1 \
  || { cat "$TB/issue.log" >&2; die "issue-client-cert failed"; }
[ -f "$CLIENT_CRT" ] && [ -f "$CLIENT_KEY" ] || die "client cert/key not written to $CLIENT_DIR"
ok "client cert $CLIENT_CRT"

# --- 6. self-check: DIRECT mTLS ---------------------------------------------
say "self-check A: direct mTLS handshake WITH client cert (expect Verify OK)"
out="$(echo Q | openssl s_client -connect "127.0.0.1:$WSS_PORT" -tls1_3 \
  -CAfile "$CA" -cert "$CLIENT_CRT" -key "$CLIENT_KEY" 2>&1 || true)"
echo "$out" | grep -q "Verify return code: 0 (ok)" \
  || { echo "$out" | tail -20 >&2; die "direct mTLS did not verify with the client cert"; }
echo "$out" | grep -qE 'New, TLSv1\.3|Protocol *: *TLSv1\.3' \
  || die "direct handshake did not negotiate TLS 1.3"
ok "direct mTLS verified (TLS 1.3, Verify OK)"

say "self-check B: direct handshake WITHOUT client cert (expect rejection)"
out="$(echo Q | openssl s_client -connect "127.0.0.1:$WSS_PORT" -tls1_3 \
  -CAfile "$CA" 2>&1 || true)"
echo "$out" | grep -qi "certificate required" \
  || { echo "$out" | tail -20 >&2; die "daemon accepted a connection without a client cert"; }
ok "unauthenticated client rejected (tls alert: certificate required)"

# --- 7. self-check: VIA RELAY -----------------------------------------------
# Drive the relay handshake then run the SAME mutual TLS over the piped stream,
# exactly as zerocode's --relay path does. Retry briefly: the daemon's relay
# bridge may take a moment to register the node-id after boot.
say "self-check C: mutual TLS end-to-end THROUGH the blind relay"
relay_check() {
  RC_HOST=127.0.0.1 RC_RELAY_PORT="$RELAY_PORT" RC_NODE="$NODE_ID" \
  RC_CA="$CA" RC_CRT="$CLIENT_CRT" RC_KEY="$CLIENT_KEY" \
  python3 - <<'PY'
import json, os, socket, ssl, sys

host = os.environ["RC_HOST"]
relay_port = int(os.environ["RC_RELAY_PORT"])
node = os.environ["RC_NODE"]

# 1. raw TCP to the relay, send Connect, read exactly one Opened line.
sock = socket.create_connection((host, relay_port), timeout=10)
sock.sendall((json.dumps({"t": "connect", "node_id": node}) + "\n").encode())
buf = b""
while not buf.endswith(b"\n"):
    chunk = sock.recv(1)
    if not chunk:
        print("relay closed before replying", file=sys.stderr); sys.exit(2)
    buf += chunk
reply = json.loads(buf.decode().strip())
if reply.get("t") != "opened":
    print(f"relay refused route: {reply}", file=sys.stderr); sys.exit(2)

# 2. run the inner mutual TLS over the piped stream; server name must match the
#    server cert SAN (127.0.0.1), not the node-id.
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
ctx.load_verify_locations(os.environ["RC_CA"])
ctx.load_cert_chain(os.environ["RC_CRT"], os.environ["RC_KEY"])
ctx.check_hostname = True
ctx.minimum_version = ssl.TLSVersion.TLSv1_3
tls = ctx.wrap_socket(sock, server_hostname=host)
ver = tls.version()
tls.close()
if ver != "TLSv1.3":
    print(f"negotiated {ver}, expected TLSv1.3", file=sys.stderr); sys.exit(2)
print("ok")
PY
}
relay_ok=0
for _ in $(seq 1 30); do
  if relay_check > "$TB/relay-check.log" 2>&1; then relay_ok=1; break; fi
  sleep 0.5
done
[ "$relay_ok" = "1" ] || { cat "$TB/relay-check.log" >&2; die "mutual TLS through the relay failed"; }
ok "mutual TLS completed end-to-end through the blind relay (TLS 1.3)"

# --- 8. done -----------------------------------------------------------------
echo
say "ALL SELF-CHECKS PASSED"

if [ "$CHECK_ONLY" = "1" ]; then
  say "--check-only: tearing down"
  exit 0
fi

cat <<EOF

------------------------------------------------------------------------------
 Live testbed is UP. Run zerocode against it (mutual TLS):

 DIRECT (zerocode -> daemon):
   $ZEROCODE \\
     --connect wss://127.0.0.1:$WSS_PORT \\
     --tls-ca-cert $CA \\
     --tls-client-cert $CLIENT_CRT \\
     --tls-client-key $CLIENT_KEY \\
     --agent <your-agent-alias>

 VIA RELAY (zerocode -> relay -> daemon):
   $ZEROCODE \\
     --connect wss://127.0.0.1:$WSS_PORT \\
     --tls-ca-cert $CA \\
     --tls-client-cert $CLIENT_CRT \\
     --tls-client-key $CLIENT_KEY \\
     --relay 127.0.0.1:$RELAY_PORT \\
     --relay-node $NODE_ID \\
     --agent <your-agent-alias>

 Logs:   daemon $TB/daemon.log   relay $TB/relay.log
 Config: $TB/config.toml

 Press Ctrl-C to stop the daemon and relay and clean up.
------------------------------------------------------------------------------
EOF

# Keep the daemon + relay alive until the operator interrupts.
wait "$DAEMON_PID"
